
@php
    $array                                     =   [];
    $top_table_section                         =   request()->input("top_table_section") ;
    $top_table_td_border_width                 =   request()->input("top_table_td_border_width") ;
    $top_table_margin_bottom                   =   request()->input("top_table_margin_bottom") ;
    $top_table_width                           =   request()->input("top_table_width") ;
    $top_table_td_border_color                 =   request()->input("top_table_td_border_color") ;
    $top_table_td_border_style                 =   request()->input("top_table_td_border_style") ;
    $left_top_table_font_size                  =   request()->input("left_top_table_font_size") ;
    $left_top_table_text_align                 =   request()->input("left_top_table_text_align") ;
    $left_top_table_width                      =   request()->input("left_top_table_width") ;
    $right_top_table_font_size                 =   request()->input("right_top_table_font_size") ;
    $right_top_table_text_align                =   request()->input("right_top_table_text_align") ;
    $right_top_table_width                     =   request()->input("right_top_table_width") ;
    $top_table_border_color                    =   request()->input("top_table_border_color") ;
    $top_table_border_style                    =   request()->input("top_table_border_style") ;
    $top_table_border_width                    =   request()->input("top_table_border_width") ;
    $content_table_section                     =   request()->input("content_table_section") ;
    $content_table_width                       =   request()->input("content_table_width") ;
    $content_width                             =   request()->input("content_width") ;
    $content_table_border_radius               =   request()->input("content_table_border_radius") ;
    $footer_table                              =   request()->input("footer_table") ;
    $content_table_th_border_color             =   request()->input("content_table_th_border_color") ;
    $content_table_th_padding                  =   request()->input("content_table_th_padding") ;
    $content_table_th_border_style             =   request()->input("content_table_th_border_style") ;
    $content_table_th_text_align               =   request()->input("content_table_th_text_align") ;
    $content_table_th_border_width             =   request()->input("content_table_th_border_width") ;
    $content_table_th_font_size                =   request()->input("content_table_th_font_size") ;
    $content_table_td_border_color             =   request()->input("content_table_td_border_color") ;
    $content_table_td_padding                  =   request()->input("content_table_td_padding") ;
    $content_table_td_border_style             =   request()->input("content_table_td_border_style") ;
    $content_table_td_text_align               =   request()->input("content_table_td_text_align") ;
    $content_table_td_border_width             =   request()->input("content_table_td_border_width") ;
    $content_table_td_font_size                =   request()->input("content_table_td_font_size") ;
    $content_table_td_no_text_align            =   request()->input("content_table_td_no_text_align") ;
    $content_table_td_no_font_size             =   request()->input("content_table_td_no_font_size") ;
    $content_table_font_weight_no              =   request()->input("content_table_font_weight_no") ;
    $table_th_no                               =   request()->input("table_th_no") ;
    $content_table_width_no                    =   request()->input("content_table_width_no") ;
    $content_table_text_align_name             =   request()->input("content_table_text_align_name") ;
    $content_table_font_size_name              =   request()->input("content_table_font_size_name") ;
    $content_table_font_weight_name            =   request()->input("content_table_font_weight_name") ;
    $table_th_name                             =   request()->input("table_th_name") ;
    $content_table_width_name                  =   request()->input("content_table_width_name") ;
    $content_table_td_qty_text_align           =   request()->input("content_table_td_qty_text_align") ;
    $content_table_td_qty_font_size            =   request()->input("content_table_td_qty_font_size") ;
    $content_table_font_weight_qty             =   request()->input("content_table_font_weight_qty") ;
    $content_table_width_qty                   =   request()->input("content_table_width_qty") ;
    $table_th_qty                              =   request()->input("table_th_qty") ;
    
    $content_table_td_code_text_align           =   request()->input("content_table_td_code_text_align") ;
    $content_table_td_code_font_size            =   request()->input("content_table_td_code_font_size") ;
    $content_table_font_weight_code             =   request()->input("content_table_font_weight_code") ;
    $content_table_width_code                   =   request()->input("content_table_width_code") ;
    $table_th_code                              =   request()->input("table_th_code") ;
    
    $content_table_td_img_text_align           =   request()->input("content_table_td_img_text_align") ;
    $content_table_td_img_font_size            =   request()->input("content_table_td_img_font_size") ;
    $content_table_font_weight_img             =   request()->input("content_table_font_weight_img") ;
    $content_table_width_img                   =   request()->input("content_table_width_img") ;
    $table_th_img                              =   request()->input("table_th_img") ;

    $content_table_td_price_bdi_text_align     =   request()->input("content_table_td_price_bdi_text_align") ;
    $content_table_td_price_bdi_font_size      =   request()->input("content_table_td_price_bdi_font_size") ;
    $content_table_font_weight_price_bdi       =   request()->input("content_table_font_weight_price_bdi") ;
    $content_table_width_price_bdi             =   request()->input("content_table_width_price_bdi") ;
    $table_th_price_bdi                        =   request()->input("table_th_price_bdi") ;

    $content_table_td_discount_text_align      =   request()->input("content_table_td_discount_text_align") ;
    $content_table_td_discount_font_size       =   request()->input("content_table_td_discount_font_size") ;
    $content_table_font_weight_discount        =   request()->input("content_table_font_weight_discount") ;
    $content_table_width_discount              =   request()->input("content_table_width_discount") ;
    $table_th_discount                         =   request()->input("table_th_discount") ;
    

    $content_table_td_price_ade_text_align     =   request()->input("content_table_td_price_ade_text_align") ;
    $content_table_td_price_ade_font_size      =   request()->input("content_table_td_price_ade_font_size") ;
    $content_table_font_weight_price_ade       =   request()->input("content_table_font_weight_price_ade") ;
    $content_table_width_price_ade             =   request()->input("content_table_width_price_ade") ;
    $table_th_price_ade                        =   request()->input("table_th_price_ade") ;

    $content_table_td_price_adi_text_align     =   request()->input("content_table_td_price_adi_text_align") ;
    $content_table_td_price_adi_font_size      =   request()->input("content_table_td_price_adi_font_size") ;
    $content_table_font_weight_price_adi       =   request()->input("content_table_font_weight_price_adi") ;
    $content_table_width_price_adi             =   request()->input("content_table_width_price_adi") ;
    $table_th_price_adi                        =   request()->input("table_th_price_adi") ;

    
    $content_table_td_subtotal_text_align      =   request()->input("content_table_td_subtotal_text_align") ;
    $content_table_td_subtotal_font_size       =   request()->input("content_table_td_subtotal_font_size") ;
    $content_table_font_weight_subtotal        =   request()->input("content_table_font_weight_subtotal") ;
    $content_table_width_subtotal              =   request()->input("content_table_width_subtotal") ;
    $table_th_subtotal                         =   request()->input("table_th_subtotal") ;

    $content_table_td_price_text_align         =   request()->input("content_table_td_price_text_align") ;
    $content_table_td_price_font_size          =   request()->input("content_table_td_price_font_size") ;
    $content_table_font_weight_price           =   request()->input("content_table_font_weight_price") ;
    $content_table_width_price                 =   request()->input("content_table_width_price") ;
    $table_th_price                            =   request()->input("table_th_price") ;
    $line_bill_table_td_margin_left            =   request()->input("line_bill_table_td_margin_left") ;
    $line_bill_table_border_color              =   request()->input("line_bill_table_border_color") ;
    $line_bill_table_border_style              =   request()->input("line_bill_table_border_style") ;
    $line_bill_table_border_width              =   request()->input("line_bill_table_border_width") ;
    $line_bill_table_color                     =   request()->input("line_bill_table_color") ;
    $line_bill_table_height                    =   request()->input("line_bill_table_height") ;
    $line_bill_table_width                     =   request()->input("line_bill_table_width") ;
    $bill_table_right_td_border_color          =   request()->input("bill_table_right_td_border_color") ;
    $bill_table_right_td_border_style          =   request()->input("bill_table_right_td_border_style") ;
    $bill_table_right_td_padding_left          =   request()->input("bill_table_right_td_padding_left") ;
    $bill_table_right_td_border_width          =   request()->input("bill_table_right_td_border_width") ;
    $bill_table_right_td_text_align            =   request()->input("bill_table_right_td_text_align") ;
    $bill_table_right_td_weight                =   request()->input("bill_table_right_td_weight") ;
    $bill_table_right_td_font_size             =   request()->input("bill_table_right_td_font_size") ;
    $bill_table_right_td_width                 =   request()->input("bill_table_right_td_width") ;
    $bill_table_left_td_border_color           =   request()->input("bill_table_left_td_border_color") ;
    $bill_table_left_td_border_style           =   request()->input("bill_table_left_td_border_style") ;
    $bill_table_left_td_padding_left           =   request()->input("bill_table_left_td_padding_left") ;
    $bill_table_left_td_border_width           =   request()->input("bill_table_left_td_border_width") ;
    $bill_table_left_td_text_align             =   request()->input("bill_table_left_td_text_align") ;
    $bill_table_left_td_weight                 =   request()->input("bill_table_left_td_weight") ;
    $bill_table_left_td_font_size              =   request()->input("bill_table_left_td_font_size") ;
    $bill_table_left_td_width                  =   request()->input("bill_table_left_td_width") ;
    $bill_table_border_color                   =   request()->input("bill_table_border_color") ;
    $bill_table_border_style                   =   request()->input("bill_table_border_style") ;
    $bill_table_border_width                   =   request()->input("bill_table_border_width") ;
    $bill_table_info_border_color              =   request()->input("bill_table_info_border_color") ;
    $bill_table_info_border_style              =   request()->input("bill_table_info_border_style") ;
    $bill_table_margin_top                     =   request()->input("bill_table_margin_top") ;
    $bill_table_info_border_width              =   request()->input("bill_table_info_border_width") ;
    $bill_table_margin_bottom                  =   request()->input("bill_table_margin_bottom") ;
    $bill_table_info_width                     =   request()->input("bill_table_info_width") ;
    $right_bottom_table_td_bor_color           =   request()->input("right_bottom_table_td_bor_color") ;
    $right_bottom_table_font_size              =   request()->input("right_bottom_table_font_size") ;
    $right_bottom_table_td_bor_style           =   request()->input("right_bottom_table_td_bor_style") ;
    $right_bottom_table_text_align             =   request()->input("right_bottom_table_text_align") ;
    $right_bottom_table_td_bor_width           =   request()->input("right_bottom_table_td_bor_width") ;
    $right_bottom_table_width                  =   request()->input("right_bottom_table_width") ;
    $left_bottom_table_td_bor_color            =   request()->input("left_bottom_table_td_bor_color") ;
    $left_bottom_table_font_size               =   request()->input("left_bottom_table_font_size") ;
    $left_bottom_table_td_bor_style            =   request()->input("left_bottom_table_td_bor_style") ;
    $left_bottom_table_text_align              =   request()->input("left_bottom_table_text_align") ;
    $left_bottom_table_td_bor_width            =   request()->input("left_bottom_table_td_bor_width") ;
    $left_bottom_table_width                   =   request()->input("left_bottom_table_width") ;
    $bottom_table_section                      =   request()->input("bottom_table_section") ;

    $body_top_left                             =   request()->input("body_top_left") ;
    $body_top_left_send_type                   =   request()->input("body_top_left_send_type") ;
    $body_top_right                            =   request()->input("body_top_right") ;
    $body_top_right_send_type                  =   request()->input("body_top_right_send_type") ;
    $body_bottom                               =   request()->input("body_bottom") ;
    $body_bottom_send_type                     =   request()->input("body_bottom_send_type") ;
    
    $table_th_no_named                         =   request()->input("table_th_no_named");       
    $table_th_code_named                       =   request()->input("table_th_code_named");       
    $table_th_name_named                       =   request()->input("table_th_name_named");       
    $table_th_img_named                        =   request()->input("table_th_img_named");       
    $table_th_qty_named                        =   request()->input("table_th_qty_named");       
    $table_th_price_named                      =   request()->input("table_th_price_named");       
    $table_th_price_bdi_named                  =   request()->input("table_th_price_bdi_named");       
    $table_th_discount_named                   =   request()->input("table_th_discount_named");       
    $table_th_price_ade_named                  =   request()->input("table_th_price_ade_named");       
    $table_th_price_adi_named                  =   request()->input("table_th_price_adi_named");       
    $table_th_subtotal_named                   =   request()->input("table_th_subtotal_named");
    
    
    $page_number_view                          =  request()->input("page_number_view");
    $currency_in_row                           =  request()->input("currency_in_row");
    $repeat_content_top                        =  request()->input("repeat_content_top");
    $if_discount_zero                          =  request()->input("if_discount_zero");
    
    $bill_invoice_info_down_vat                =  request()->input("bill_invoice_info_down_vat");
    $bill_invoice_info_down_subtotal           =  request()->input("bill_invoice_info_down_subtotal");
    $bill_invoice_info_down_discount           =  request()->input("bill_invoice_info_down_discount");
    $bill_invoice_info_down_subtotal_after_dis =  request()->input("bill_invoice_info_down_subtotal_after_dis");
    
    $class_width_left                          =  request()->input("class_width_left");
    $class_width_right                         =  request()->input("class_width_right");
    $bold_left_invoice_info                    =  request()->input("bold_left_invoice_info");
    $bold_left_invoice_info_br_width           =  request()->input("bold_left_invoice_info_br_width");
    $bold_left_invoice_info_br_style           =  request()->input("bold_left_invoice_info_br_style");
    $bold_left_invoice_info_br_color           =  request()->input("bold_left_invoice_info_br_color");
    $bold_left_invoice_info_text_align         =  request()->input("bold_left_invoice_info_text_align");
   
    $class_width_left_right                    =  request()->input("class_width_left_right");
    $class_width_right_right                   =  request()->input("class_width_right_right");
    $bold_right_invoice_info                   =  request()->input("bold_right_invoice_info");
    $bold_right_invoice_info_br_width          =  request()->input("bold_right_invoice_info_br_width");
    $bold_right_invoice_info_br_style          =  request()->input("bold_right_invoice_info_br_style");
    $bold_right_invoice_info_br_color          =  request()->input("bold_right_invoice_info_br_color");
    $bold_right_invoice_info_text_align        =  request()->input("bold_right_invoice_info_text_align");
    
    $bold_left_invoice_info_customer_number    =  request()->input("bold_left_invoice_info_customer_number");
    $bold_left_invoice_info_customer_address   =  request()->input("bold_left_invoice_info_customer_address");
    $bold_left_invoice_info_customer_mobile    =  request()->input("bold_left_invoice_info_customer_mobile");
    $bold_left_invoice_info_customer_tax       =  request()->input("bold_left_invoice_info_customer_tax");
    
    $bold_left_invoice_info_number             =  request()->input("bold_left_invoice_info_number");
    $bold_left_invoice_info_project            =  request()->input("bold_left_invoice_info_project");
    $bold_left_invoice_info_date               =  request()->input("bold_left_invoice_info_date");
    
    $margin_top_page                           =  request()->input("margin_top_page");
    $margin_bottom_page                        =  request()->input("margin_bottom_page");

    $left_invoice_info                         =  request()->input("left_invoice_info");
    $color_invoice_info                        =  request()->input("color_invoice_info");
    $right_invoice_info                        =  request()->input("right_invoice_info");
    $padding_invoice_info                      =  request()->input("padding_invoice_info");
    $background_color_invoice_info             =  request()->input("background_color_invoice_info");
    
    $body_content_top                         =  request()->input("body_content_top");
    $body_content_margin_left                 =  request()->input("body_content_margin_left");
    $body_content_margin_right                =  request()->input("body_content_margin_right");
    $body_content_margin_bottom               =  request()->input("body_content_margin_bottom");
    
    $invoice_no                               =  request()->input("invoice_no");
    $project_no                               =  request()->input("project_no");
    $date_name                                =  request()->input("date_name");
    $customer_no                              =  request()->input("customer_no");
    $address_name                             =  request()->input("address_name");
    $mobile_name                              =  request()->input("mobile_name");
    $tax_name                                 =  request()->input("tax_name");
    
    $show_quotation_terms                     =  request()->input("show_quotation_terms");
    $show_customer_signature                  =  request()->input("show_customer_signature");

    $array      = [  
        "edit_type"                           => (request()->input("edit_type"))?request()->input("edit_type"):null,
        "top_table_section"                   => $top_table_section,
        "top_table_td_border_width"           => $top_table_td_border_width,
        "top_table_margin_bottom"             => $top_table_margin_bottom,
        "top_table_width"                     => $top_table_width,
        "top_table_td_border_color"           => $top_table_td_border_color,
        "top_table_td_border_style"           => $top_table_td_border_style,
        "left_top_table_font_size"            => $left_top_table_font_size,
        "left_top_table_text_align"           => $left_top_table_text_align,
        "left_top_table_width"                => $left_top_table_width,
        "right_top_table_font_size"           => $right_top_table_font_size,
        "right_top_table_text_align"          => $right_top_table_text_align,
        "right_top_table_width"               => $right_top_table_width,
        "top_table_border_color"              => $top_table_border_color,
        "top_table_border_style"              => $top_table_border_style,
        "top_table_border_width"              => $top_table_border_width,
        "content_table_section"               => $content_table_section,
        "content_table_width"                 => $content_table_width,
        "content_width"                       => $content_width,
        "content_table_border_radius"         => $content_table_border_radius,
        "footer_table"                        => $footer_table,
        "content_table_th_border_color"       => $content_table_th_border_color,
        "content_table_th_padding"            => $content_table_th_padding,
        "content_table_th_border_style"       => $content_table_th_border_style,
        "content_table_th_text_align"         => $content_table_th_text_align,
        "content_table_th_border_width"       => $content_table_th_border_width,
        "content_table_th_font_size"          => $content_table_th_font_size,
        "content_table_td_border_color"       => $content_table_td_border_color,
        "content_table_td_padding"            => $content_table_td_padding,
        "content_table_td_border_style"       => $content_table_td_border_style,
        "content_table_td_text_align"         => $content_table_td_text_align,
        "content_table_td_border_width"       => $content_table_td_border_width,
        "content_table_td_font_size"          => $content_table_td_font_size,
        "content_table_td_no_text_align"      => $content_table_td_no_text_align,
        "content_table_td_no_font_size"       => $content_table_td_no_font_size,
        "content_table_font_weight_no"        => $content_table_font_weight_no,
        "table_th_no"                         => $table_th_no,
        "content_table_width_no"              => $content_table_width_no,
        "content_table_text_align_name"       => $content_table_text_align_name,
        "content_table_font_size_name"        => $content_table_font_size_name,
        "content_table_font_weight_name"      => $content_table_font_weight_name,
        "table_th_name"                       => $table_th_name,
        "content_table_width_name"            => $content_table_width_name,
        "content_table_td_qty_text_align"     => $content_table_td_qty_text_align,
        "content_table_td_qty_font_size"      => $content_table_td_qty_font_size,
        "content_table_font_weight_qty"       => $content_table_font_weight_qty,
        "content_table_width_qty"             => $content_table_width_qty,
        "table_th_qty"                        => $table_th_qty,
        "content_table_td_code_text_align"     => $content_table_td_code_text_align,
        "content_table_td_code_font_size"      => $content_table_td_code_font_size,
        "content_table_font_weight_code"       => $content_table_font_weight_code,
        "content_table_width_code"             => $content_table_width_code,
        "table_th_code"                        => $table_th_code,
        "content_table_td_img_text_align"     => $content_table_td_img_text_align,
        "content_table_td_img_font_size"      => $content_table_td_img_font_size,
        "content_table_font_weight_img"       => $content_table_font_weight_img,
        "content_table_width_img"             => $content_table_width_img,
        "table_th_img"                        => $table_th_img,
        "content_table_td_discount_text_align"     => $content_table_td_discount_text_align,
        "content_table_td_discount_font_size"      => $content_table_td_discount_font_size,
        "content_table_font_weight_discount"       => $content_table_font_weight_discount,
        "content_table_width_discount"             => $content_table_width_discount,
        "table_th_discount"                        => $table_th_discount,
        "content_table_td_subtotal_text_align"     => $content_table_td_subtotal_text_align,
        "content_table_td_subtotal_font_size"      => $content_table_td_subtotal_font_size,
        "content_table_font_weight_subtotal"       => $content_table_font_weight_subtotal,
        "content_table_width_subtotal"             => $content_table_width_subtotal,
        "table_th_subtotal"                        => $table_th_subtotal,
        "content_table_td_price_bdi_text_align"  => $content_table_td_price_bdi_text_align,
        "content_table_td_price_bdi_font_size"   => $content_table_td_price_bdi_font_size,
        "content_table_font_weight_price_bdi"    => $content_table_font_weight_price_bdi,
        "content_table_width_price_bdi"          => $content_table_width_price_bdi,
        "table_th_price_bdi"                     => $table_th_price_bdi,
        "content_table_td_price_ade_text_align"  => $content_table_td_price_ade_text_align,
        "content_table_td_price_ade_font_size"   => $content_table_td_price_ade_font_size,
        "content_table_font_weight_price_ade"    => $content_table_font_weight_price_ade,
        "content_table_width_price_ade"          => $content_table_width_price_ade,
        "table_th_price_ade"                     => $table_th_price_ade,
        "content_table_td_price_adi_text_align"  => $content_table_td_price_adi_text_align,
        "content_table_td_price_adi_font_size"   => $content_table_td_price_adi_font_size,
        "content_table_font_weight_price_adi"    => $content_table_font_weight_price_adi,
        "content_table_width_price_adi"          => $content_table_width_price_adi,
        "table_th_price_adi"                     => $table_th_price_adi,
        "content_table_td_price_text_align"   => $content_table_td_price_text_align,
        "content_table_td_price_font_size"    => $content_table_td_price_font_size,
        "content_table_font_weight_price"     => $content_table_font_weight_price,
        "content_table_width_price"           => $content_table_width_price,
        "table_th_price"                      => $table_th_price,
        "line_bill_table_td_margin_left"      => $line_bill_table_td_margin_left,
        "line_bill_table_border_color"        => $line_bill_table_border_color,
        "line_bill_table_border_style"        => $line_bill_table_border_style,
        "line_bill_table_border_width"        => $line_bill_table_border_width,
        "line_bill_table_color"               => $line_bill_table_color,
        "line_bill_table_height"              => $line_bill_table_height,
        "line_bill_table_width"               => $line_bill_table_width,
        "bill_table_right_td_border_color"    => $bill_table_right_td_border_color,
        "bill_table_right_td_border_style"    => $bill_table_right_td_border_style,
        "bill_table_right_td_padding_left"    => $bill_table_right_td_padding_left,
        "bill_table_right_td_border_width"    => $bill_table_right_td_border_width,
        "bill_table_right_td_text_align"      => $bill_table_right_td_text_align,
        "bill_table_right_td_weight"          => $bill_table_right_td_weight,
        "bill_table_right_td_font_size"       => $bill_table_right_td_font_size,
        "bill_table_right_td_width"           => $bill_table_right_td_width,
        "bill_table_left_td_border_color"     => $bill_table_left_td_border_color,
        "bill_table_left_td_border_style"     => $bill_table_left_td_border_style,
        "bill_table_left_td_padding_left"     => $bill_table_left_td_padding_left,
        "bill_table_left_td_border_width"     => $bill_table_left_td_border_width,
        "bill_table_left_td_text_align"       => $bill_table_left_td_text_align,
        "bill_table_left_td_weight"           => $bill_table_left_td_weight,
        "bill_table_left_td_font_size"        => $bill_table_left_td_font_size,
        "bill_table_left_td_width"            => $bill_table_left_td_width,
        "bill_table_border_color"             => $bill_table_border_color,
        "bill_table_border_style"             => $bill_table_border_style,
        "bill_table_border_width"             => $bill_table_border_width,
        "bill_table_info_border_color"        => $bill_table_info_border_color,
        "bill_table_info_border_style"        => $bill_table_info_border_style,
        "bill_table_margin_top"               => $bill_table_margin_top,
        "bill_table_info_border_width"        => $bill_table_info_border_width,
        "bill_table_margin_bottom"            => $bill_table_margin_bottom,
        "bill_table_info_width"               => $bill_table_info_width,
        "right_bottom_table_td_bor_color"     => $right_bottom_table_td_bor_color,
        "right_bottom_table_font_size"        => $right_bottom_table_font_size,
        "right_bottom_table_td_bor_style"     => $right_bottom_table_td_bor_style,
        "right_bottom_table_text_align"       => $right_bottom_table_text_align,
        "right_bottom_table_td_bor_width"     => $right_bottom_table_td_bor_width,
        "right_bottom_table_width"            => $right_bottom_table_width,
        "left_bottom_table_td_bor_color"      => $left_bottom_table_td_bor_color,
        "left_bottom_table_font_size"         => $left_bottom_table_font_size,
        "left_bottom_table_td_bor_style"      => $left_bottom_table_td_bor_style,
        "left_bottom_table_text_align"        => $left_bottom_table_text_align,
        "left_bottom_table_td_bor_width"      => $left_bottom_table_td_bor_width,
        "left_bottom_table_width"             => $left_bottom_table_width,
        "bottom_table_section"                => $bottom_table_section,
        "body_top_left"                       => $body_top_left,
        "body_top_left_send_type"             => $body_top_left_send_type,
        "body_top_right"                      => $body_top_right,
        "body_top_right_send_type"            => $body_top_right_send_type,
        "body_bottom"                         => $body_bottom,
        "body_bottom_send_type"               => $body_bottom_send_type,
        "table_th_no_named"                   => $table_th_no_named,
        "table_th_code_named"                 => $table_th_code_named,
        "table_th_name_named"                 => $table_th_name_named,
        "table_th_img_named"                  => $table_th_img_named,
        "table_th_qty_named"                  => $table_th_qty_named,
        "table_th_price_named"                => $table_th_price_named,
        "table_th_price_bdi_named"            => $table_th_price_bdi_named,
        "table_th_discount_named"             => $table_th_discount_named,
        "table_th_price_ade_named"            => $table_th_price_ade_named,
        "table_th_price_adi_named"            => $table_th_price_adi_named,
        "table_th_subtotal_named"             => $table_th_subtotal_named,
        "left_invoice_info"                   => $left_invoice_info,
        "color_invoice_info"                  => $color_invoice_info,
        "right_invoice_info"                  => $right_invoice_info,
        "padding_invoice_info"                => $padding_invoice_info,
        "background_color_invoice_info"       => $background_color_invoice_info,
        "class_width_left_right"              => $class_width_left_right,
        "class_width_right_right"             => $class_width_right_right,
        "bold_right_invoice_info"             => $bold_right_invoice_info,
        "bold_right_invoice_info_br_width"    => $bold_right_invoice_info_br_width,
        "bold_right_invoice_info_br_style"    => $bold_right_invoice_info_br_style,
        "bold_right_invoice_info_br_color"    => $bold_right_invoice_info_br_color,
        "bold_right_invoice_info_text_align"  => $bold_right_invoice_info_text_align,
        "bold_left_invoice_info_customer_number"  => $bold_left_invoice_info_customer_number,
        "bold_left_invoice_info_customer_address" => $bold_left_invoice_info_customer_address,
        "bold_left_invoice_info_customer_mobile"  => $bold_left_invoice_info_customer_mobile,
        "bold_left_invoice_info_customer_tax"     => $bold_left_invoice_info_customer_tax,
        "bold_left_invoice_info_number"           => $bold_left_invoice_info_number,
        "bold_left_invoice_info_project"          => $bold_left_invoice_info_project,
        "bold_left_invoice_info_date"             => $bold_left_invoice_info_date,
        "currency_in_row"                         => $currency_in_row,
        "repeat_content_top"                      => $repeat_content_top,
        "page_number_view"                        => $page_number_view,
        "if_discount_zero"                        => $if_discount_zero,
        "bill_invoice_info_down_vat"              => $bill_invoice_info_down_vat,
        "bill_invoice_info_down_subtotal"         => $bill_invoice_info_down_subtotal,
        "bill_invoice_info_down_discount"         => $bill_invoice_info_down_discount,
        "bill_invoice_info_down_subtotal_after_dis"  => $bill_invoice_info_down_subtotal_after_dis,
        "class_width_left"                        => $class_width_left,
        "class_width_right"                       => $class_width_right,
        "bold_left_invoice_info"                  => $bold_left_invoice_info,
        "bold_left_invoice_info_br_width"         => $bold_left_invoice_info_br_width,
        "bold_left_invoice_info_br_style"         => $bold_left_invoice_info_br_style,
        "bold_left_invoice_info_br_color"         => $bold_left_invoice_info_br_color,
        "bold_left_invoice_info_text_align"       => $bold_left_invoice_info_text_align,
       
        "margin_top_page"                         => $margin_top_page,
        "margin_bottom_page"                      => $margin_bottom_page,
        
        "body_content_top"                        => $body_content_top,
        "body_content_margin_left"                => $body_content_margin_left,
        "body_content_margin_right"               => $body_content_margin_right,
        "body_content_margin_bottom"              => $body_content_margin_bottom,
        
        "invoice_no"                              => $invoice_no,
        "project_no"                              => $project_no,
        "date_name"                               => $date_name,
        
        "customer_no"                             => $customer_no,
        "address_name"                            => $address_name,
        "mobile_name"                             => $mobile_name,
        "tax_name"                                => $tax_name,

        "show_quotation_terms"                    => $show_quotation_terms,
        "show_customer_signature"                 => $show_customer_signature,
        
    ];
 
@endphp

 
@include("printer.body",["array"=>$array])
 
 