
@php
    $array                              =   [];
    $footer_font_size                   =   request()->input("footer_font_size") ;
    $footer_width                       =   request()->input("footer_width") ;
    $footer_text_align                  =   request()->input("footer_text_align")  ;
    $footer_style                       =   request()->input("footer_style")  ;
    $footer_view                        =   request()->input("footer_view")  ;
    $footer_weight                      =   request()->input("footer_weight")  ;
    $footer_border_width                =   request()->input("footer_border_width")  ;
    $footer_border_style                =   request()->input("footer_border_style")  ;
    $footer_border_color                =   request()->input("footer_border_color")  ;
    $footer_padding_top                 =   request()->input("footer_padding_top")  ;
    $footer_padding_left                =   request()->input("footer_padding_left")  ;
    $footer_padding_right               =   request()->input("footer_padding_right")  ;
    $footer_padding_bottom              =   request()->input("footer_padding_bottom")  ;
    $footer_style_letter                =   request()->input("footer_style_letter")  ;
    $footer_position                    =   request()->input("footer_position")  ;
    $footer_top                         =   request()->input("footer_top")  ;
    $footer_left                        =   request()->input("footer_left")  ;
    $page_number_view                   =   request()->input("page_number_view")  ;
    $footer_right                       =   request()->input("footer_right")  ;
    $footer_bottom                      =   request()->input("footer_bottom")  ;
    $footer_image_box_height            =   request()->input("footer_image_box_height") ;
    $footer_box_image_color             =   request()->input("footer_box_image_color") ;
    $footer_box_image_background        =   request()->input("footer_box_image_background") ;
    $footer_image_border_color          =   request()->input("footer_image_border_color") ;
    $footer_image_border_style          =   request()->input("footer_image_border_style") ;
    $footer_image_view                  =   request()->input("footer_image_view") ;
    $position_img_footer                =   request()->input("position_img_footer") ;
    $align_image_footer                 =   request()->input("align_image_footer") ;
    $footer_image_width                 =   request()->input("footer_image_width") ;
    $footer_image_height                =   request()->input("footer_image_height") ;
    $footer_image_border_width          =   request()->input("footer_image_border_width") ;
    $footer_image_border_radius         =   request()->input("footer_image_border_radius") ;
    $footer_other_view                  =   request()->input("footer_other_view") ;
    $footer_line_view                   =   request()->input("footer_line_view") ;
    $footer_line_border_color           =   request()->input("footer_line_border_color") ;
    $footer_line_border_style           =   request()->input("footer_line_border_style") ;
    $footer_line_border_width           =   request()->input("footer_line_border_width") ;
    $footer_line_radius                 =   request()->input("footer_line_radius") ;
    $footer_line_width                  =   request()->input("footer_line_width") ;
    $footer_line_radius                 =   request()->input("footer_line_radius") ;
    $footer_line_height                 =   request()->input("footer_line_height") ;
    $footer_line_radius                 =   request()->input("footer_line_radius") ;
    $footer_line_color                  =   request()->input("footer_line_color") ;
    $footer_line_margin_top             =   request()->input("footer_line_margin_top") ;
    $footer_line_margin_bottom          =   request()->input("footer_line_margin_bottom") ;
    $footer_other_border_color          =   request()->input("footer_other_border_color") ;
    $footer_other_border_style          =   request()->input("footer_other_border_style") ;
    $footer_other_border_width          =   request()->input("footer_other_border_width") ;
    $footer_other_border_radius         =   request()->input("footer_other_border_radius") ;
    $footer_other_width                 =   request()->input("footer_other_width") ;
    $other_background_footer            =   request()->input("other_background_footer") ;
    $align_other_footer                 =   request()->input("align_other_footer") ;
    $footer_address_align               =   request()->input("footer_address_align") ;
    $footer_address_font_size           =   request()->input("footer_address_font_size") ;
    $footer_address_width               =   request()->input("footer_address_width") ;
    $footer_address_letter              =   request()->input("footer_address_letter") ;
    $footer_address_border_width        =   request()->input("footer_address_border_width") ;
    $footer_address_border_style        =   request()->input("footer_address_border_style") ;
    $footer_address_border_color        =   request()->input("footer_address_border_color") ;
    $footer_address_position            =   request()->input("footer_address_position") ;
    $footer_address_top                 =   request()->input("footer_address_top") ;
    $footer_address_left                =   request()->input("footer_address_left") ;
    $footer_address_right               =   request()->input("footer_address_right") ;
    $footer_address_bottom              =   request()->input("footer_address_bottom") ;
    $footer_address_padding_top         =   request()->input("footer_address_padding_top") ;
    $footer_address_padding_left        =   request()->input("footer_address_padding_left") ;
    $footer_address_padding_right       =   request()->input("footer_address_padding_right") ;
    $footer_address_padding_bottom      =   request()->input("footer_address_padding_bottom") ;
    $footer_tax_align                   =   request()->input("footer_tax_align") ;
    $footer_tax_font_size               =   request()->input("footer_tax_font_size") ;
    $footer_tax_width                   =   request()->input("footer_tax_width") ;
    $footer_tax_letter                  =   request()->input("footer_tax_letter") ;
    $footer_tax_border_width            =   request()->input("footer_tax_border_width") ;
    $footer_tax_border_style            =   request()->input("footer_tax_border_style") ;
    $footer_tax_border_color            =   request()->input("footer_tax_border_color") ;
    $footer_tax_position                =   request()->input("footer_tax_position") ;
    $footer_tax_top                     =   request()->input("footer_tax_top") ;
    $footer_tax_left                    =   request()->input("footer_tax_left") ;
    $footer_tax_right                   =   request()->input("footer_tax_right") ;
    $footer_tax_bottom                  =   request()->input("footer_tax_bottom") ;
    $footer_tax_padding_top             =   request()->input("footer_tax_padding_top") ;
    $footer_tax_padding_left            =   request()->input("footer_tax_padding_left") ;
    $footer_tax_padding_right           =   request()->input("footer_tax_padding_right") ;
    $footer_tax_padding_bottom          =   request()->input("footer_tax_padding_bottom") ;
    $footer_bill_align                  =   request()->input("footer_bill_align") ;
    $footer_bill_font_size              =   request()->input("footer_bill_font_size") ;
    $footer_bill_width                  =   request()->input("footer_bill_width") ;
    $footer_bill_letter                 =   request()->input("footer_bill_letter") ;
    $footer_bill_border_width           =   request()->input("footer_bill_border_width") ;
    $footer_bill_border_style           =   request()->input("footer_bill_border_style") ;
    $footer_bill_border_color           =   request()->input("footer_bill_border_color") ;
    $footer_bill_position               =   request()->input("footer_bill_position") ;
    $footer_bill_top                    =   request()->input("footer_bill_top") ;
    $footer_bill_left                   =   request()->input("footer_bill_left") ;
    $footer_bill_right                  =   request()->input("footer_bill_right") ;
    $footer_bill_bottom                 =   request()->input("footer_bill_bottom") ;
    $footer_bill_padding_top            =   request()->input("footer_bill_padding_top") ;
    $footer_bill_padding_left           =   request()->input("footer_bill_padding_left") ;
    $footer_bill_padding_right          =   request()->input("footer_bill_padding_right") ;
    $footer_bill_padding_bottom         =   request()->input("footer_bill_padding_bottom") ;
   
    $footer_other_position              =   request()->input("footer_other_position") ;
    $footer_other_top                   =   request()->input("footer_other_top") ;
    $footer_other_left                  =   request()->input("footer_other_left") ;
    $footer_other_right                 =   request()->input("footer_other_right") ;
    $footer_other_bottom                =   request()->input("footer_other_bottom") ;
    
    $footer_box_width                   =   request()->input("footer_box_width") ;
    
    $footer_box_border_radius           =   request()->input("footer_box_border_radius") ;
    $footer_box_border_width            =   request()->input("footer_box_border_width") ;
    $footer_box_border_style            =   request()->input("footer_box_border_style") ;
    $footer_box_border_color            =   request()->input("footer_box_border_color") ;
    $footer_box_background              =   request()->input("footer_box_background") ;
    
    $footer_box_border_radius           =   request()->input("footer_box_border_radius") ;
    $footer_box_border_width            =   request()->input("footer_box_border_width") ;
    $footer_box_border_style            =   request()->input("footer_box_border_style") ;
    $footer_box_border_color            =   request()->input("footer_box_border_color") ;
    $footer_box_background              =   request()->input("footer_box_background") ;

    $footer_image_box_width             =   request()->input("footer_image_box_width") ;
    $footer_image_box_margin            =   request()->input("footer_image_box_margin") ;
    $footer_image_box_border_radius     =   request()->input("footer_image_box_border_radius") ;
    $footer_image_box_border_width      =   request()->input("footer_image_box_border_width") ;
    $footer_image_box_border_style      =   request()->input("footer_image_box_border_style") ;
    $footer_image_box_border_color      =   request()->input("footer_image_box_border_color") ;
    $position_box_footer_align          =   request()->input("position_box_footer_align") ;
    $footer_image_box_background        =   request()->input("footer_image_box_background") ;
    $footer_table_width                 =   request()->input("footer_table_width") ;
    $footer_table_color                 =   request()->input("footer_table_color") ;
    $footer_table_radius                =   request()->input("footer_table_radius") ;


    // ....................................................
    $left_footer                        =   request()->input("left_footer") ;
    $left_footer_send_type              =   request()->input("left_footer_send_type") ;
    $center_top_footer                  =   request()->input("center_top_footer") ;
    $center_top_footer_send_type        =   request()->input("center_top_footer_send_type") ;
    $center_middle_footer               =   request()->input("center_middle_footer") ;
    $center_middle_footer_send_type     =   request()->input("center_middle_footer_send_type") ;
    $center_last_footer                 =   request()->input("center_last_footer") ;
    $center_last_footer_send_type       =   request()->input("center_last_footer_send_type") ;

    $array      = [  
        "edit_type"                         => (request()->input("edit_type"))?request()->input("edit_type"):null,
        "footer_font_size"                  => $footer_font_size,
        "footer_width"                      => $footer_width,
        "footer_text_align"                 => $footer_text_align,
        "footer_style"                      => $footer_style,
        "footer_view"                       => $footer_view,
        "footer_weight"                     => $footer_weight,
        "footer_border_width"               => $footer_border_width,
        "footer_border_style"               => $footer_border_style,
        "footer_border_color"               => $footer_border_color,
        "footer_padding_top"                => $footer_padding_top,
        "footer_padding_left"               => $footer_padding_left,
        "footer_padding_right"              => $footer_padding_right,
        "footer_padding_bottom"             => $footer_padding_bottom,
        "footer_style_letter"               => $footer_style_letter,
        "footer_position"                   => $footer_position,
        "footer_top"                        => $footer_top,
        "footer_left"                       => $footer_left,
        "footer_right"                      => $footer_right,
        "footer_bottom"                     => $footer_bottom,
        "footer_image_box_height"           => $footer_image_box_height,
        "footer_box_image_color"            => $footer_box_image_color,
        "footer_box_image_background"       => $footer_box_image_background,
        "footer_image_border_color"         => $footer_image_border_color,
        "footer_image_border_style"         => $footer_image_border_style,
        "footer_image_view"                 => $footer_image_view,
        "position_img_footer"               => $position_img_footer,
        "align_image_footer"                => $align_image_footer,
        "footer_image_width"                => $footer_image_width,
        "footer_image_height"               => $footer_image_height,
        "footer_image_border_width"         => $footer_image_border_width,
        "footer_image_border_radius"        => $footer_image_border_radius,
        "footer_other_view"                 => $footer_other_view,
        "footer_line_view"                  => $footer_line_view,
        "footer_line_border_color"          => $footer_line_border_color,
        "footer_line_border_style"          => $footer_line_border_style,
        "footer_line_border_width"          => $footer_line_border_width,
        "footer_line_radius"                => $footer_line_radius,
        "footer_line_width"                 => $footer_line_width,
        "footer_line_radius"                => $footer_line_radius,
        "footer_line_height"                => $footer_line_height,
        "footer_line_radius"                => $footer_line_radius,
        "footer_line_color"                 => $footer_line_color,
        "footer_line_margin_top"            => $footer_line_margin_top,
        "footer_line_margin_bottom"         => $footer_line_margin_bottom,
        "footer_other_border_color"         => $footer_other_border_color,
        "footer_other_border_style"         => $footer_other_border_style,
        "footer_other_border_width"         => $footer_other_border_width,
        "footer_other_border_radius"        => $footer_other_border_radius,
        "footer_other_width"                => $footer_other_width,
        "other_background_footer"           => $other_background_footer,
        "align_other_footer"                => $align_other_footer,
        
        "footer_address_align"              => $footer_address_align,
        "footer_address_font_size"          => $footer_address_font_size,
        "footer_address_width"              => $footer_address_width,
        "footer_address_letter"             => $footer_address_letter,
        "footer_address_border_width"       => $footer_address_border_width,
        "footer_address_border_style"       => $footer_address_border_style,
        "footer_address_border_color"       => $footer_address_border_color,
        "footer_address_position"           => $footer_address_position,
        "footer_address_top"                => $footer_address_top,
        "footer_address_left"               => $footer_address_left,
        "footer_address_right"              => $footer_address_right,
        "footer_address_bottom"             => $footer_address_bottom,
        "footer_address_padding_top"        => $footer_address_padding_top,
        "footer_address_padding_left"       => $footer_address_padding_left,
        "footer_address_padding_right"      => $footer_address_padding_right,
        "footer_address_padding_bottom"     => $footer_address_padding_bottom,
        "footer_tax_align"                  => $footer_tax_align,
        "footer_tax_font_size"              => $footer_tax_font_size,
        "footer_tax_width"                  => $footer_tax_width,
        "footer_tax_letter"                 => $footer_tax_letter,
        "footer_tax_border_width"           => $footer_tax_border_width,
        "footer_tax_border_style"           => $footer_tax_border_style,
        "footer_tax_border_color"           => $footer_tax_border_color,
        "footer_tax_position"               => $footer_tax_position,
        "footer_tax_top"                    => $footer_tax_top,
        "footer_tax_left"                   => $footer_tax_left,
        "footer_tax_right"                  => $footer_tax_right,
        "footer_tax_bottom"                 => $footer_tax_bottom,
        "footer_tax_padding_top"            => $footer_tax_padding_top,
        "footer_tax_padding_left"           => $footer_tax_padding_left,
        "footer_tax_padding_right"          => $footer_tax_padding_right,
        "footer_tax_padding_bottom"         => $footer_tax_padding_bottom,
        "footer_bill_align"                 => $footer_bill_align,
        "footer_bill_font_size"             => $footer_bill_font_size,
        "footer_bill_width"                 => $footer_bill_width,
        "footer_bill_letter"                => $footer_bill_letter,
        "footer_bill_border_width"          => $footer_bill_border_width,
        "footer_bill_border_style"          => $footer_bill_border_style,
        "footer_bill_border_color"          => $footer_bill_border_color,
        "footer_bill_position"              => $footer_bill_position,
        "footer_bill_top"                   => $footer_bill_top,
        "footer_bill_left"                  => $footer_bill_left,
        "footer_bill_right"                 => $footer_bill_right,
        "footer_bill_bottom"                => $footer_bill_bottom,
        "footer_bill_padding_top"           => $footer_bill_padding_top,
        "footer_bill_padding_left"          => $footer_bill_padding_left,
        "footer_bill_padding_right"         => $footer_bill_padding_right,
        "footer_bill_padding_bottom"        => $footer_bill_padding_bottom,

        "footer_other_position"             => $footer_other_position,
        "footer_other_top"                  => $footer_other_top,
        "footer_other_left"                 => $footer_other_left,
        "footer_other_right"                => $footer_other_right,
        "footer_other_bottom"               => $footer_other_bottom,

        "footer_box_width"                  => $footer_box_width,
        "footer_box_border_radius"          => $footer_box_border_radius,
        "footer_box_border_width"           => $footer_box_border_width,
        "footer_box_border_style"           => $footer_box_border_style,
        "footer_box_border_color"           => $footer_box_border_color,
        "footer_box_background"             => $footer_box_background,
        "footer_image_box_width"            => $footer_image_box_width,
        "footer_image_box_margin"           => $footer_image_box_margin,
        "footer_image_box_border_radius"    => $footer_image_box_border_radius,
        "footer_image_box_border_width"     => $footer_image_box_border_width,
        "footer_image_box_border_style"     => $footer_image_box_border_style,
        "footer_image_box_border_color"     => $footer_image_box_border_color,
        "position_box_footer_align"         => $position_box_footer_align,
        "footer_image_box_background"       => $footer_image_box_background,
        "footer_table_width"                => $footer_table_width,
        "footer_table_color"                => $footer_table_color,
        "footer_table_radius"               => $footer_table_radius,
        "left_footer"                       => $left_footer,
        "left_footer_send_type"             => $left_footer_send_type,
        "center_top_footer"                 => $center_top_footer,
        "center_top_footer_send_type"       => $center_top_footer_send_type,
        "center_middle_footer"              => $center_middle_footer,
        "center_middle_footer_send_type"    => $center_middle_footer_send_type,
        "center_last_footer"                => $center_last_footer,
        "center_last_footer_send_type"      => $center_last_footer_send_type,
        "page_number_view"                  => $page_number_view,
        ];
   
@endphp

 
@include("printer.footer",["array"=>$array])
 
 