
@php
    $array                              =   [];
    $header_font_size                   =   request()->input("header_font_size") ;
    $header_width                       =   request()->input("header_width") ;
    $header_text_align                  =   request()->input("header_text_align")  ;
    $header_style                       =   request()->input("header_style")  ;
    $header_view                        =   request()->input("header_view")  ;
    $header_weight                      =   request()->input("header_weight")  ;
    $header_border_width                =   request()->input("header_border_width")  ;
    $header_border_style                =   request()->input("header_border_style")  ;
    $header_border_color                =   request()->input("header_border_color")  ;
    $header_padding_top                 =   request()->input("header_padding_top")  ;
    $header_padding_left                =   request()->input("header_padding_left")  ;
    $header_padding_right               =   request()->input("header_padding_right")  ;
    $header_padding_bottom              =   request()->input("header_padding_bottom")  ;
    $header_style_letter                =   request()->input("header_style_letter")  ;
    $header_position                    =   request()->input("header_position")  ;
    $header_top                         =   request()->input("header_top")  ;
    $header_left                        =   request()->input("header_left")  ;
    $header_right                       =   request()->input("header_right")  ;
    $header_bottom                      =   request()->input("header_bottom")  ;
    $header_image_box_height            =   request()->input("header_image_box_height") ;
    $header_box_image_color             =   request()->input("header_box_image_color") ;
    $header_box_image_background        =   request()->input("header_box_image_background") ;
    $header_image_border_color          =   request()->input("header_image_border_color") ;
    $header_image_border_style          =   request()->input("header_image_border_style") ;
    $header_image_view                  =   request()->input("header_image_view") ;
    $position_img_header                =   request()->input("position_img_header") ;
    $align_image_header                 =   request()->input("align_image_header") ;
    $header_image_width                 =   request()->input("header_image_width") ;
    $header_image_height                =   request()->input("header_image_height") ;
    $header_image_border_width          =   request()->input("header_image_border_width") ;
    $header_image_border_radius         =   request()->input("header_image_border_radius") ;
    $header_other_view                  =   request()->input("header_other_view") ;
    $header_line_view                   =   request()->input("header_line_view") ;
    $header_line_border_color           =   request()->input("header_line_border_color") ;
    $header_line_border_style           =   request()->input("header_line_border_style") ;
    $header_line_border_width           =   request()->input("header_line_border_width") ;
    $header_line_radius                 =   request()->input("header_line_radius") ;
    $header_line_width                  =   request()->input("header_line_width") ;
    $header_line_radius                 =   request()->input("header_line_radius") ;
    $header_line_height                 =   request()->input("header_line_height") ;
    $header_line_radius                 =   request()->input("header_line_radius") ;
    $header_line_color                  =   request()->input("header_line_color") ;
    $header_line_margin_top             =   request()->input("header_line_margin_top") ;
    $header_other_border_color          =   request()->input("header_other_border_color") ;
    $header_other_border_style          =   request()->input("header_other_border_style") ;
    $header_other_border_width          =   request()->input("header_other_border_width") ;
    $header_other_border_radius         =   request()->input("header_other_border_radius") ;
    $header_other_width                 =   request()->input("header_other_width") ;
    $other_background_header            =   request()->input("other_background_header") ;
    $align_other_header                 =   request()->input("align_other_header") ;
    $header_address_align               =   request()->input("header_address_align") ;
    $header_address_font_size           =   request()->input("header_address_font_size") ;
    $header_address_width               =   request()->input("header_address_width") ;
    $header_address_letter              =   request()->input("header_address_letter") ;
    $header_address_border_width        =   request()->input("header_address_border_width") ;
    $header_address_border_style        =   request()->input("header_address_border_style") ;
    $header_address_border_color        =   request()->input("header_address_border_color") ;
    $header_address_position            =   request()->input("header_address_position") ;
    $header_address_top                 =   request()->input("header_address_top") ;
    $header_address_left                =   request()->input("header_address_left") ;
    $header_address_right               =   request()->input("header_address_right") ;
    $header_address_bottom              =   request()->input("header_address_bottom") ;
    $header_address_padding_top         =   request()->input("header_address_padding_top") ;
    $header_address_padding_left        =   request()->input("header_address_padding_left") ;
    $header_address_padding_right       =   request()->input("header_address_padding_right") ;
    $header_address_padding_bottom      =   request()->input("header_address_padding_bottom") ;
    $header_tax_align                   =   request()->input("header_tax_align") ;
    $header_tax_font_size               =   request()->input("header_tax_font_size") ;
    $header_tax_width                   =   request()->input("header_tax_width") ;
    $header_tax_letter                  =   request()->input("header_tax_letter") ;
    $header_tax_border_width            =   request()->input("header_tax_border_width") ;
    $header_tax_border_style            =   request()->input("header_tax_border_style") ;
    $header_tax_border_color            =   request()->input("header_tax_border_color") ;
    $header_tax_position                =   request()->input("header_tax_position") ;
    $header_tax_top                     =   request()->input("header_tax_top") ;
    $header_tax_left                    =   request()->input("header_tax_left") ;
    $header_tax_right                   =   request()->input("header_tax_right") ;
    $header_tax_bottom                  =   request()->input("header_tax_bottom") ;
    $header_tax_padding_top             =   request()->input("header_tax_padding_top") ;
    $header_tax_padding_left            =   request()->input("header_tax_padding_left") ;
    $header_tax_padding_right           =   request()->input("header_tax_padding_right") ;
    $header_tax_padding_bottom          =   request()->input("header_tax_padding_bottom") ;
    $header_bill_align                  =   request()->input("header_bill_align") ;
    $header_bill_font_size              =   request()->input("header_bill_font_size") ;
    $header_bill_width                  =   request()->input("header_bill_width") ;
    $header_bill_letter                 =   request()->input("header_bill_letter") ;
    $header_bill_border_width           =   request()->input("header_bill_border_width") ;
    $header_bill_border_style           =   request()->input("header_bill_border_style") ;
    $header_bill_border_color           =   request()->input("header_bill_border_color") ;
    $header_bill_position               =   request()->input("header_bill_position") ;
    $header_bill_top                    =   request()->input("header_bill_top") ;
    $header_bill_left                   =   request()->input("header_bill_left") ;
    $header_bill_right                  =   request()->input("header_bill_right") ;
    $header_bill_bottom                 =   request()->input("header_bill_bottom") ;
    $header_bill_padding_top            =   request()->input("header_bill_padding_top") ;
    $header_bill_padding_left           =   request()->input("header_bill_padding_left") ;
    $header_bill_padding_right          =   request()->input("header_bill_padding_right") ;
    $header_bill_padding_bottom         =   request()->input("header_bill_padding_bottom") ;
   
    $header_other_position              =   request()->input("header_other_position") ;
    $header_other_top                   =   request()->input("header_other_top") ;
    $header_other_left                  =   request()->input("header_other_left") ;
    $header_other_right                 =   request()->input("header_other_right") ;
    $header_other_bottom                =   request()->input("header_other_bottom") ;
    
    $header_box_width                   =   request()->input("header_box_width") ;
    
    $header_box_border_radius           =   request()->input("header_box_border_radius") ;
    $header_box_border_width            =   request()->input("header_box_border_width") ;
    $header_box_border_style            =   request()->input("header_box_border_style") ;
    $header_box_border_color            =   request()->input("header_box_border_color") ;
    $header_box_background              =   request()->input("header_box_background") ;
    
    $header_box_border_radius           =   request()->input("header_box_border_radius") ;
    $header_box_border_width            =   request()->input("header_box_border_width") ;
    $header_box_border_style            =   request()->input("header_box_border_style") ;
    $header_box_border_color            =   request()->input("header_box_border_color") ;
    $header_box_background              =   request()->input("header_box_background") ;

    $header_image_box_width             =   request()->input("header_image_box_width") ;
    $header_image_box_margin            =   request()->input("header_image_box_margin") ;
    $header_image_box_border_radius     =   request()->input("header_image_box_border_radius") ;
    $header_image_box_border_width      =   request()->input("header_image_box_border_width") ;
    $header_image_box_border_style      =   request()->input("header_image_box_border_style") ;
    $header_image_box_border_color      =   request()->input("header_image_box_border_color") ;
    $position_box_header_align          =   request()->input("position_box_header_align") ;
    $header_image_box_background        =   request()->input("header_image_box_background") ;
    $header_table_width                 =   request()->input("header_table_width") ;
    $header_table_color                 =   request()->input("header_table_color") ;
    $header_table_radius                =   request()->input("header_table_radius") ;
    
    // ....................................................
    $left_header                        =   request()->input("left_header") ;
    $repeat_content_top                 =   request()->input("repeat_content_top") ;
    $page_number_view                   =   request()->input("page_number_view") ;
    $left_header_send_type              =   request()->input("left_header_send_type") ;
    $center_top_header                  =   request()->input("center_top_header") ;
    $center_top_header_send_type        =   request()->input("center_top_header_send_type") ;
    $center_middle_header               =   request()->input("center_middle_header") ;
    $center_middle_header_send_type     =   request()->input("center_middle_header_send_type") ;
    $center_last_header                 =   request()->input("center_last_header") ;
    $center_last_header_send_type       =   request()->input("center_last_header_send_type") ;
    
    $invoice_no                         =   request()->input("invoice_no") ;
    $project_no                         =   request()->input("project_no") ;
    $date_name                          =   request()->input("date_name") ;
    $customer_no                        =   request()->input("customer_no") ;
    $address_name                       =   request()->input("address_name") ;
    $mobile_name                        =   request()->input("mobile_name") ;
    $tax_name                           =   request()->input("tax_name") ;
    
    $array      = [  
        "edit_type"                    => (request()->input("edit_type"))?request()->input("edit_type"):null,
        "header_font_size"             => $header_font_size,
        "header_width"                 => $header_width,
        "header_text_align"            => $header_text_align,
        "header_style"                 => $header_style,
        "header_view"                  => $header_view,
        "header_weight"                => $header_weight,
        "header_border_width"          => $header_border_width,
        "header_border_style"          => $header_border_style,
        "header_border_color"          => $header_border_color,
        "header_padding_top"           => $header_padding_top,
        "header_padding_left"          => $header_padding_left,
        "header_padding_right"         => $header_padding_right,
        "header_padding_bottom"        => $header_padding_bottom,
        "header_style_letter"          => $header_style_letter,
        "header_position"              => $header_position,
        "header_top"                   => $header_top,
        "header_left"                  => $header_left,
        "header_right"                 => $header_right,
        "header_bottom"                => $header_bottom,
        "header_image_box_height"      => $header_image_box_height,
        "header_box_image_color"       => $header_box_image_color,
        "header_box_image_background"  => $header_box_image_background,
        "header_image_border_color"    => $header_image_border_color,
        "header_image_border_style"    => $header_image_border_style,
        "header_image_view"            => $header_image_view,
        "position_img_header"          => $position_img_header,
        "align_image_header"           => $align_image_header,
        "header_image_width"           => $header_image_width,
        "header_image_height"          => $header_image_height,
        "header_image_border_width"    => $header_image_border_width,
        "header_image_border_radius"   => $header_image_border_radius,
        "header_other_view"            => $header_other_view,
        "header_line_view"             => $header_line_view,
        "header_line_border_color"     => $header_line_border_color,
        "header_line_border_style"     => $header_line_border_style,
        "header_line_border_width"     => $header_line_border_width,
        "header_line_radius"           => $header_line_radius,
        "header_line_width"            => $header_line_width,
        "repeat_content_top"           => $repeat_content_top,
        "header_line_radius"           => $header_line_radius,
        "header_line_height"           => $header_line_height,
        "header_line_radius"           => $header_line_radius,
        "header_line_color"            => $header_line_color,
        "header_line_margin_top"       => $header_line_margin_top,
        "header_other_border_color"    => $header_other_border_color,
        "header_other_border_style"    => $header_other_border_style,
        "header_other_border_width"    => $header_other_border_width,
        "header_other_border_radius"   => $header_other_border_radius,
        "header_other_width"           => $header_other_width,
        "other_background_header"      => $other_background_header,
        "align_other_header"           => $align_other_header,
        
        "header_address_align"             => $header_address_align,
        "header_address_font_size"         => $header_address_font_size,
        "header_address_width"             => $header_address_width,
        "header_address_letter"            => $header_address_letter,
        "header_address_border_width"      => $header_address_border_width,
        "header_address_border_style"      => $header_address_border_style,
        "header_address_border_color"      => $header_address_border_color,
        "header_address_position"          => $header_address_position,
        "header_address_top"               => $header_address_top,
        "header_address_left"              => $header_address_left,
        "header_address_right"             => $header_address_right,
        "header_address_bottom"            => $header_address_bottom,
        "header_address_padding_top"       => $header_address_padding_top,
        "header_address_padding_left"      => $header_address_padding_left,
        "header_address_padding_right"     => $header_address_padding_right,
        "header_address_padding_bottom"    => $header_address_padding_bottom,
        "header_tax_align"                 => $header_tax_align,
        "header_tax_font_size"             => $header_tax_font_size,
        "header_tax_width"                 => $header_tax_width,
        "header_tax_letter"                => $header_tax_letter,
        "header_tax_border_width"          => $header_tax_border_width,
        "header_tax_border_style"          => $header_tax_border_style,
        "header_tax_border_color"          => $header_tax_border_color,
        "header_tax_position"              => $header_tax_position,
        "header_tax_top"                   => $header_tax_top,
        "header_tax_left"                  => $header_tax_left,
        "header_tax_right"                 => $header_tax_right,
        "header_tax_bottom"                => $header_tax_bottom,
        "header_tax_padding_top"           => $header_tax_padding_top,
        "header_tax_padding_left"          => $header_tax_padding_left,
        "header_tax_padding_right"         => $header_tax_padding_right,
        "header_tax_padding_bottom"        => $header_tax_padding_bottom,
        "header_bill_align"                => $header_bill_align,
        "header_bill_font_size"            => $header_bill_font_size,
        "header_bill_width"                => $header_bill_width,
        "header_bill_letter"               => $header_bill_letter,
        "header_bill_border_width"         => $header_bill_border_width,
        "header_bill_border_style"         => $header_bill_border_style,
        "header_bill_border_color"         => $header_bill_border_color,
        "header_bill_position"             => $header_bill_position,
        "header_bill_top"                  => $header_bill_top,
        "header_bill_left"                 => $header_bill_left,
        "header_bill_right"                => $header_bill_right,
        "header_bill_bottom"               => $header_bill_bottom,
        "header_bill_padding_top"          => $header_bill_padding_top,
        "header_bill_padding_left"         => $header_bill_padding_left,
        "header_bill_padding_right"        => $header_bill_padding_right,
        "header_bill_padding_bottom"       => $header_bill_padding_bottom,  
        "header_other_position"            => $header_other_position,
        "header_other_top"                 => $header_other_top,
        "header_other_left"                => $header_other_left,
        "header_other_right"               => $header_other_right,
        "header_other_bottom"              => $header_other_bottom,

        "header_box_width"                  => $header_box_width,
        "header_box_border_radius"          => $header_box_border_radius,
        "header_box_border_width"           => $header_box_border_width,
        "header_box_border_style"           => $header_box_border_style,
        "header_box_border_color"           => $header_box_border_color,
        "header_box_background"             => $header_box_background,
        "header_image_box_width"            => $header_image_box_width,
        "header_image_box_margin"           => $header_image_box_margin,
        "header_image_box_border_radius"    => $header_image_box_border_radius,
        "header_image_box_border_width"     => $header_image_box_border_width,
        "header_image_box_border_style"     => $header_image_box_border_style,
        "header_image_box_border_color"     => $header_image_box_border_color,
        "position_box_header_align"         => $position_box_header_align,
        "header_image_box_background"       => $header_image_box_background,
        "header_table_width"                => $header_table_width,
        "header_table_color"                => $header_table_color,
        "header_table_radius"               => $header_table_radius,
        "left_header"                       => $left_header,
        "left_header_send_type"             => $left_header_send_type,
        "center_top_header"                 => $center_top_header,
        "center_top_header_send_type"       => $center_top_header_send_type,
        "center_middle_header"              => $center_middle_header,
        "center_middle_header_send_type"    => $center_middle_header_send_type,
        "center_last_header"                => $center_last_header,
        "center_last_header_send_type"      => $center_last_header_send_type,
        "page_number_view"                  => $page_number_view,
        "invoice_no"                        => $invoice_no,
        "project_no"                        => $project_no,
        "date_name"                         => $date_name,
        "customer_no"                       => $customer_no,
        "address_name"                      => $address_name,
        "mobile_name"                       => $mobile_name,
        "tax_name"                          => $tax_name,

        ];
   
@endphp

 
@include("printer.header",["array"=>$array])
 
 