<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\PrinterContentTemplate;
use App\Models\PrinterFooterTemplate;
use App\Models\PrinterTemplateContain;

class PrinterTemplate extends Model
{
    use HasFactory,SoftDeletes;

    // store
    public static function storeTemplate($data,$request){
        $size  = $data->only("Paper-size","Form-type","Pattern-type","Voucher-type","Cheque-type");
        $type  = "";
        if($size["Form-type"] == "Sale"){
            $type  = $size["Pattern-type"];
        }elseif($size["Form-type"] == "Return_Sale"){
            $type  = $size["Pattern-type"];
        }elseif($size["Form-type"] == "Voucher"){
            $type  = $size["Voucher-type"];
        }elseif($size["Form-type"] == "Cheques"){
            $type  = $size["Cheque-type"];
        }else{
            $type  = null;
        }
         
        $printerTemplate                                    =  new PrinterTemplate();
        $printerTemplate->business_id                       =  auth()->user()->business_id;
        $printerTemplate->name_template                     =  $data->name_template;
        $printerTemplate->page_size                         =  $size["Paper-size"];
        $printerTemplate->Form_type                         =  $size["Form-type"];
        $printerTemplate->type                              =  $type;
        $printerTemplate->header_view                       =  ($data->header_view)?true:false;
        $printerTemplate->style_header                      =  $data->style_header;
        $printerTemplate->header_width                      =  $data->header_width;
        $printerTemplate->header_style_letter               =  $data->header_style_letter;
        $printerTemplate->header_table_width                =  $data->header_table_width;
        $printerTemplate->header_table_color                =  $data->header_table_color;
        $printerTemplate->header_table_radius               =  $data->header_table_radius;
        $printerTemplate->align_text_header                 =  $data->align_text_header;
        $printerTemplate->header_font_size                  =  $data->header_font_size;
        $printerTemplate->header_font_weight                =  $data->header_font_weight;
        $printerTemplate->header_border_width               =  $data->header_border_width;
        $printerTemplate->header_border_style               =  $data->header_border_style;
        $printerTemplate->header_border_color               =  $data->header_border_color;
        $printerTemplate->header_padding_left               =  $data->header_padding_left;
        $printerTemplate->header_padding_top                =  $data->header_padding_top;
        $printerTemplate->header_padding_right              =  $data->header_padding_right;
        $printerTemplate->header_padding_bottom             =  $data->header_padding_bottom;
        $printerTemplate->header_position                   =  $data->header_position;
        $printerTemplate->header_top                        =  $data->header_top;
        $printerTemplate->header_bottom                     =  $data->header_bottom;
        $printerTemplate->header_left                       =  $data->header_left;
        $printerTemplate->header_right                      =  $data->header_right;
        $printerTemplate->header_box_width                  =  $data->header_box_width;
        $printerTemplate->header_box_border_style           =  $data->header_box_border_style;
        $printerTemplate->header_box_border_width           =  $data->header_box_border_width;
        $printerTemplate->header_box_background             =  $data->header_box_background;
        $printerTemplate->header_box_border_color           =  $data->header_box_border_color;
        $printerTemplate->header_box_border_radius          =  $data->header_box_border_radius;
        $printerTemplate->header_image_view                 =  ($data->header_image_view)?true:false;
        $printerTemplate->align_image_header                =  $data->align_image_header;
        $printerTemplate->position_img_header               =  $data->position_img_header;
        $printerTemplate->header_image_width                =  $data->header_image_width;
        $printerTemplate->header_image_height               =  $data->header_image_height;
        $printerTemplate->header_image_border_width         =  $data->header_image_border_width;
        $printerTemplate->header_image_border_color         =  $data->header_image_border_color;
        $printerTemplate->header_image_border_style         =  $data->header_image_border_style;
        $printerTemplate->header_image_border_radius        =  $data->header_image_border_radius;
        $printerTemplate->header_image_box_width            =  $data->header_image_box_width;
        $printerTemplate->header_image_box_height           =  $data->header_image_box_height;
        $printerTemplate->header_image_box_margin           =  $data->header_image_box_margin;
        $printerTemplate->header_box_image_background       =  $data->header_box_image_background;
        $printerTemplate->header_box_image_color            =  $data->header_box_image_color;
        $printerTemplate->position_box_header_align         =  $data->position_box_header_align;
        $printerTemplate->header_image_box_background       =  $data->header_image_box_background;
        $printerTemplate->header_image_box_border_width     =  $data->header_image_box_border_width;
        $printerTemplate->header_image_box_border_style     =  $data->header_image_box_border_style;
        $printerTemplate->header_image_box_border_color     =  $data->header_image_box_border_color;
        $printerTemplate->header_image_box_border_radius    =  $data->header_image_box_border_radius;
        $printerTemplate->header_other_view                 =  ($data->header_other_view)?true:false;
        $printerTemplate->align_other_header                =  $data->align_other_header;
        $printerTemplate->other_background_header           =  $data->other_background_header;
        $printerTemplate->header_other_width                =  $data->header_other_width;
        $printerTemplate->header_other_border_radius        =  $data->header_other_border_radius;
        $printerTemplate->header_other_border_width         =  $data->header_other_border_width;
        $printerTemplate->header_other_border_style         =  $data->header_other_border_style;
        $printerTemplate->header_other_border_color         =  $data->header_other_border_color;
        $printerTemplate->header_other_position             =  $data->header_other_position;
        $printerTemplate->header_other_top                  =  $data->header_other_top;
        $printerTemplate->header_other_left                 =  $data->header_other_left;
        $printerTemplate->header_other_right                =  $data->header_other_right;
        $printerTemplate->header_other_bottom               =  $data->header_other_bottom;
        $printerTemplate->header_tax_align                  =  $data->header_tax_align;
        $printerTemplate->header_tax_font_size              =  $data->header_tax_font_size;
        $printerTemplate->header_tax_width                  =  $data->header_tax_width;
        $printerTemplate->header_tax_letter                 =  $data->header_tax_letter;
        $printerTemplate->header_tax_border_width           =  $data->header_tax_border_width;
        $printerTemplate->header_tax_border_style           =  $data->header_tax_border_style;
        $printerTemplate->header_tax_border_color           =  $data->header_tax_border_color;
        $printerTemplate->header_tax_padding_top            =  $data->header_tax_padding_top;
        $printerTemplate->header_tax_padding_left           =  $data->header_tax_padding_left;
        $printerTemplate->header_tax_padding_right          =  $data->header_tax_padding_right;
        $printerTemplate->header_tax_padding_bottom         =  $data->header_tax_padding_bottom;
        $printerTemplate->header_tax_position               =  $data->header_tax_position;
        $printerTemplate->header_tax_top                    =  $data->header_tax_top;
        $printerTemplate->header_tax_bottom                 =  $data->header_tax_bottom;
        $printerTemplate->header_tax_left                   =  $data->header_tax_left;
        $printerTemplate->header_tax_right                  =  $data->header_tax_right;
        $printerTemplate->header_address_align              =  $data->header_address_align;
        $printerTemplate->header_address_font_size          =  $data->header_address_font_size;
        $printerTemplate->header_address_width              =  $data->header_address_width;
        $printerTemplate->header_address_letter             =  $data->header_address_letter;
        $printerTemplate->header_address_border_width       =  $data->header_address_border_width;
        $printerTemplate->header_address_border_style       =  $data->header_address_border_style;
        $printerTemplate->header_address_border_color       =  $data->header_address_border_color;
        $printerTemplate->header_address_padding_top        =  $data->header_address_padding_top;
        $printerTemplate->header_address_padding_left       =  $data->header_address_padding_left;
        $printerTemplate->header_address_padding_right      =  $data->header_address_padding_right;
        $printerTemplate->header_address_padding_bottom     =  $data->header_address_padding_bottom;
        $printerTemplate->header_address_position           =  $data->header_address_position;
        $printerTemplate->header_address_top                =  $data->header_address_top;
        $printerTemplate->header_address_bottom             =  $data->header_address_bottom;
        $printerTemplate->header_address_left               =  $data->header_address_left;
        $printerTemplate->header_address_right              =  $data->header_address_right;
        $printerTemplate->header_bill_align                 =  $data->header_bill_align;
        $printerTemplate->header_bill_font_size             =  $data->header_bill_font_size;
        $printerTemplate->header_bill_width                 =  $data->header_bill_width;
        $printerTemplate->header_bill_letter                =  $data->header_bill_letter;
        $printerTemplate->header_bill_border_width          =  $data->header_bill_border_width;
        $printerTemplate->header_bill_border_style          =  $data->header_bill_border_style;
        $printerTemplate->header_bill_border_color          =  $data->header_bill_border_color;
        $printerTemplate->header_bill_padding_top           =  $data->header_bill_padding_top;
        $printerTemplate->header_bill_padding_left          =  $data->header_bill_padding_left;
        $printerTemplate->header_bill_padding_right         =  $data->header_bill_padding_right;
        $printerTemplate->header_bill_padding_bottom        =  $data->header_bill_padding_bottom;
        $printerTemplate->header_bill_position              =  $data->header_bill_position;
        $printerTemplate->header_bill_top                   =  $data->header_bill_top;
        $printerTemplate->header_bill_bottom                =  $data->header_bill_bottom;
        $printerTemplate->header_bill_left                  =  $data->header_bill_left;
        $printerTemplate->header_bill_right                 =  $data->header_bill_right;
        $printerTemplate->header_line_view                  =  ($data->header_line_view)?true:false;
        $printerTemplate->header_line_height                =  $data->header_line_height;
        $printerTemplate->header_line_width                 =  $data->header_line_width;
        $printerTemplate->header_line_color                 =  $data->header_line_color;
        $printerTemplate->header_line_margin_top            =  $data->header_line_margin_top;
        $printerTemplate->header_line_radius                =  $data->header_line_radius;
        $printerTemplate->header_line_border_width          =  $data->header_line_border_width;
        $printerTemplate->header_line_border_style          =  $data->header_line_border_style;
        $printerTemplate->header_line_border_color          =  $data->header_line_border_color;
        $printerTemplate->save();
        // ........... content
        $printerContentTemplate                                    =  new PrinterContentTemplate();
        $printerContentTemplate->printer_template_id               =  $printerTemplate->id;
        $printerContentTemplate->top_table_section                 =  ($data->top_table_section)?true:false;
        $printerContentTemplate->top_table_margin_bottom           =  $data->top_table_margin_bottom;
        $printerContentTemplate->top_table_width                   =  $data->top_table_width;
        $printerContentTemplate->top_table_td_border_width         =  $data->top_table_td_border_width;
        $printerContentTemplate->top_table_td_border_style         =  $data->top_table_td_border_style;
        $printerContentTemplate->top_table_td_border_color         =  $data->top_table_td_border_color;
        $printerContentTemplate->left_top_table_width              =  $data->left_top_table_width;
        $printerContentTemplate->left_top_table_text_align         =  $data->left_top_table_text_align;
        $printerContentTemplate->left_top_table_font_size          =  $data->left_top_table_font_size;
        $printerContentTemplate->right_top_table_width             =  $data->right_top_table_width;
        $printerContentTemplate->right_top_table_text_align        =  $data->right_top_table_text_align;
        $printerContentTemplate->right_top_table_font_size         =  $data->right_top_table_font_size;
        $printerContentTemplate->top_table_border_width            =  $data->top_table_border_width;
        $printerContentTemplate->top_table_border_style            =  $data->top_table_border_style;
        $printerContentTemplate->top_table_border_color            =  $data->top_table_border_color;
        $printerContentTemplate->content_table_section             =  ($data->content_table_section)?true:false;
        $printerContentTemplate->content_table_width               =  $data->content_table_width;
        $printerContentTemplate->content_width                     =  $data->content_width;
        $printerContentTemplate->content_table_border_radius       =  $data->content_table_border_radius;
        $printerContentTemplate->footer_table                      =  $data->footer_table;  
        $printerContentTemplate->content_table_th_font_size        =  $data->content_table_th_font_size;
        $printerContentTemplate->content_table_th_border_width     =  $data->content_table_th_border_width;
        $printerContentTemplate->content_table_th_text_align       =  $data->content_table_th_text_align;
        $printerContentTemplate->content_table_th_border_style     =  $data->content_table_th_border_style;
        $printerContentTemplate->content_table_th_padding          =  $data->content_table_th_padding;
        $printerContentTemplate->content_table_th_border_color     =  $data->content_table_th_border_color;
        $printerContentTemplate->content_table_td_font_size        =  $data->content_table_td_font_size;
        $printerContentTemplate->content_table_td_border_width     =  $data->content_table_td_border_width;
        $printerContentTemplate->content_table_td_text_align       =  $data->content_table_td_text_align;
        $printerContentTemplate->content_table_td_border_style     =  $data->content_table_td_border_style;
        $printerContentTemplate->content_table_td_padding          =  $data->content_table_td_padding;
        $printerContentTemplate->content_table_td_border_color     =  $data->content_table_td_border_color;
        $printerContentTemplate->table_th_no                       =  $data->table_th_no;
        $printerContentTemplate->content_table_width_no            =  $data->content_table_width_no;
        $printerContentTemplate->content_table_font_weight_no      =  $data->content_table_font_weight_no;
        $printerContentTemplate->content_table_td_no_font_size     =  $data->content_table_td_no_font_size;
        $printerContentTemplate->content_table_td_no_text_align    =  $data->content_table_td_no_text_align;
        $printerContentTemplate->table_th_name                     =  $data->table_th_name;
        $printerContentTemplate->content_table_width_name          =  $data->content_table_width_name;
        $printerContentTemplate->content_table_font_weight_name    =  $data->content_table_font_weight_name;
        $printerContentTemplate->content_table_font_size_name      =  $data->content_table_font_size_name;
        $printerContentTemplate->content_table_text_align_name     =  $data->content_table_text_align_name;
        
        $printerContentTemplate->table_th_qty                      =  $data->table_th_qty;
        $printerContentTemplate->content_table_width_qty           =  $data->content_table_width_qty;
        $printerContentTemplate->content_table_font_weight_qty     =  $data->content_table_font_weight_qty;
        $printerContentTemplate->content_table_td_qty_font_size    =  $data->content_table_td_qty_font_size;
        $printerContentTemplate->content_table_td_qty_text_align   =  $data->content_table_td_qty_text_align;
        
        $printerContentTemplate->table_th_img                      =  $data->table_th_img;
        $printerContentTemplate->content_table_width_img           =  $data->content_table_width_img;
        $printerContentTemplate->content_table_font_weight_img     =  $data->content_table_font_weight_img;
        $printerContentTemplate->content_table_td_img_font_size    =  $data->content_table_td_img_font_size;
        $printerContentTemplate->content_table_td_img_text_align   =  $data->content_table_td_img_text_align;
        
        $printerContentTemplate->table_th_code                     =  $data->table_th_code;
        $printerContentTemplate->content_table_width_code          =  $data->content_table_width_code;
        $printerContentTemplate->content_table_font_weight_code    =  $data->content_table_font_weight_code;
        $printerContentTemplate->content_table_td_code_font_size   =  $data->content_table_td_code_font_size;
        $printerContentTemplate->content_table_td_code_text_align  =  $data->content_table_td_code_text_align;
        
        $printerContentTemplate->table_th_discount                      =  $data->table_th_discount;
        $printerContentTemplate->content_table_width_discount           =  $data->content_table_width_discount;
        $printerContentTemplate->content_table_font_weight_discount     =  $data->content_table_font_weight_discount;
        $printerContentTemplate->content_table_td_discount_font_size    =  $data->content_table_td_discount_font_size;
        $printerContentTemplate->content_table_td_discount_text_align   =  $data->content_table_td_discount_text_align;
        
        $printerContentTemplate->table_th_subtotal                      =  $data->table_th_subtotal;
        $printerContentTemplate->content_table_width_subtotal           =  $data->content_table_width_subtotal;
        $printerContentTemplate->content_table_font_weight_subtotal     =  $data->content_table_font_weight_subtotal;
        $printerContentTemplate->content_table_td_subtotal_font_size    =  $data->content_table_td_subtotal_font_size;
        $printerContentTemplate->content_table_td_subtotal_text_align   =  $data->content_table_td_subtotal_text_align;

        $printerContentTemplate->table_th_price                    =  $data->table_th_price;
        $printerContentTemplate->content_table_width_price         =  $data->content_table_width_price;
        $printerContentTemplate->content_table_font_weight_price   =  $data->content_table_font_weight_price;
        $printerContentTemplate->content_table_td_price_font_size  =  $data->content_table_td_price_font_size;
        $printerContentTemplate->content_table_td_price_text_align =  $data->content_table_td_price_text_align;

        $printerContentTemplate->table_th_price_bdi                    =  $data->table_th_price_bdi;
        $printerContentTemplate->content_table_width_price_bdi         =  $data->content_table_width_price_bdi;
        $printerContentTemplate->content_table_font_weight_price_bdi   =  $data->content_table_font_weight_price_bdi;
        $printerContentTemplate->content_table_td_price_bdi_font_size  =  $data->content_table_td_price_bdi_font_size;
        $printerContentTemplate->content_table_td_price_bdi_text_align =  $data->content_table_td_price_bdi_text_align;

        $printerContentTemplate->table_th_price_ade                    =  $data->table_th_price_ade;
        $printerContentTemplate->content_table_width_price_ade         =  $data->content_table_width_price_ade;
        $printerContentTemplate->content_table_font_weight_price_ade   =  $data->content_table_font_weight_price_ade;
        $printerContentTemplate->content_table_td_price_ade_font_size  =  $data->content_table_td_price_ade_font_size;
        $printerContentTemplate->content_table_td_price_ade_text_align =  $data->content_table_td_price_ade_text_align;

        $printerContentTemplate->table_th_price_adi                    =  $data->table_th_price_adi;
        $printerContentTemplate->content_table_width_price_adi         =  $data->content_table_width_price_adi;
        $printerContentTemplate->content_table_font_weight_price_adi   =  $data->content_table_font_weight_price_adi;
        $printerContentTemplate->content_table_td_price_adi_font_size  =  $data->content_table_td_price_adi_font_size;
        $printerContentTemplate->content_table_td_price_adi_text_align =  $data->content_table_td_price_adi_text_align;



        $printerContentTemplate->bottom_table_section              =  ($data->bottom_table_section)?true:false;
        $printerContentTemplate->left_bottom_table_width           =  $data->left_bottom_table_width;
        $printerContentTemplate->left_bottom_table_td_bor_width    =  $data->left_bottom_table_td_bor_width;
        $printerContentTemplate->left_bottom_table_text_align      =  $data->left_bottom_table_text_align;
        $printerContentTemplate->left_bottom_table_td_bor_style    =  $data->left_bottom_table_td_bor_style;
        $printerContentTemplate->left_bottom_table_font_size       =  $data->left_bottom_table_font_size;
        $printerContentTemplate->left_bottom_table_td_bor_color    =  $data->left_bottom_table_td_bor_color;
        $printerContentTemplate->right_bottom_table_width          =  $data->right_bottom_table_width;
        $printerContentTemplate->right_bottom_table_td_bor_width   =  $data->right_bottom_table_td_bor_width;
        $printerContentTemplate->right_bottom_table_text_align     =  $data->right_bottom_table_text_align;
        $printerContentTemplate->right_bottom_table_td_bor_style   =  $data->right_bottom_table_td_bor_style;
        $printerContentTemplate->right_bottom_table_font_size      =  $data->right_bottom_table_font_size;
        $printerContentTemplate->right_bottom_table_td_bor_color   =  $data->right_bottom_table_td_bor_color;
        $printerContentTemplate->bill_table_info_width             =  $data->bill_table_info_width;
        $printerContentTemplate->bill_table_margin_bottom          =  $data->bill_table_margin_bottom;
        $printerContentTemplate->bill_table_info_border_width      =  $data->bill_table_info_border_width;
        $printerContentTemplate->bill_table_margin_top             =  $data->bill_table_margin_top;
        $printerContentTemplate->bill_table_info_border_style      =  $data->bill_table_info_border_style;
        $printerContentTemplate->bill_table_info_border_color      =  $data->bill_table_info_border_color;
        $printerContentTemplate->bill_table_border_width           =  $data->bill_table_border_width;
        $printerContentTemplate->bill_table_border_style           =  $data->bill_table_border_style;
        $printerContentTemplate->bill_table_border_color           =  $data->bill_table_border_color;
        $printerContentTemplate->bill_table_left_td_width          =  $data->bill_table_left_td_width;
        $printerContentTemplate->bill_table_left_td_font_size      =  $data->bill_table_left_td_font_size;
        $printerContentTemplate->bill_table_left_td_weight         =  $data->bill_table_left_td_weight;
        $printerContentTemplate->bill_table_left_td_text_align     =  $data->bill_table_left_td_text_align;
        $printerContentTemplate->bill_table_left_td_border_width   =  $data->bill_table_left_td_border_width;
        $printerContentTemplate->bill_table_left_td_padding_left   =  $data->bill_table_left_td_padding_left;
        $printerContentTemplate->bill_table_left_td_border_style   =  $data->bill_table_left_td_border_style;
        $printerContentTemplate->bill_table_left_td_border_color   =  $data->bill_table_left_td_border_color;
        $printerContentTemplate->bill_table_right_td_width         =  $data->bill_table_right_td_width;
        $printerContentTemplate->bill_table_right_td_font_size     =  $data->bill_table_right_td_font_size;
        $printerContentTemplate->bill_table_right_td_weight        =  $data->bill_table_right_td_weight;
        $printerContentTemplate->bill_table_right_td_text_align    =  $data->bill_table_right_td_text_align;
        $printerContentTemplate->bill_table_right_td_border_width  =  $data->bill_table_right_td_border_width;
        $printerContentTemplate->bill_table_right_td_padding_left  =  $data->bill_table_right_td_padding_left;
        $printerContentTemplate->bill_table_right_td_border_style  =  $data->bill_table_right_td_border_style;
        $printerContentTemplate->bill_table_right_td_border_color  =  $data->bill_table_right_td_border_color;
        $printerContentTemplate->line_bill_table_width             =  $data->line_bill_table_width;
        $printerContentTemplate->line_bill_table_height            =  $data->line_bill_table_height;
        $printerContentTemplate->line_bill_table_color             =  $data->line_bill_table_color;
        $printerContentTemplate->line_bill_table_border_width      =  $data->line_bill_table_border_width;
        $printerContentTemplate->line_bill_table_border_style      =  $data->line_bill_table_border_style;
        $printerContentTemplate->line_bill_table_border_color      =  $data->line_bill_table_border_color;
        $printerContentTemplate->line_bill_table_td_margin_left    =  $data->line_bill_table_td_margin_left;
        
        $printerContentTemplate->table_th_no_named                         =  $data->table_th_no_named;
        $printerContentTemplate->table_th_code_named                       =  $data->table_th_code_named;
        $printerContentTemplate->table_th_name_named                       =  $data->table_th_name_named;
        $printerContentTemplate->table_th_img_named                        =  $data->table_th_img_named;
        $printerContentTemplate->table_th_qty_named                        =  $data->table_th_qty_named;
        $printerContentTemplate->table_th_price_named                      =  $data->table_th_price_named;
        $printerContentTemplate->table_th_price_bdi_named                  =  $data->table_th_price_bdi_named;
        $printerContentTemplate->table_th_discount_named                   =  $data->table_th_discount_named;
        $printerContentTemplate->table_th_price_ade_named                  =  $data->table_th_price_ade_named;
        $printerContentTemplate->table_th_price_adi_named                  =  $data->table_th_price_adi_named;
        $printerContentTemplate->table_th_subtotal_named                   =  $data->table_th_subtotal_named;

        $printerContentTemplate->left_invoice_info                         = $data->left_invoice_info ; 
        $printerContentTemplate->color_invoice_info                        = $data->color_invoice_info ; 
        $printerContentTemplate->right_invoice_info                        = $data->right_invoice_info ; 
        $printerContentTemplate->padding_invoice_info                      = $data->padding_invoice_info ; 
        $printerContentTemplate->background_color_invoice_info             = $data->background_color_invoice_info ; 
        $printerContentTemplate->class_width_left_right                    = $data->class_width_left_right ; 
        $printerContentTemplate->class_width_right_right                   = $data->class_width_right_right ; 
        $printerContentTemplate->bold_right_invoice_info                   = $data->bold_right_invoice_info ; 
        $printerContentTemplate->bold_right_invoice_info_br_width          = $data->bold_right_invoice_info_br_width ; 
        $printerContentTemplate->bold_right_invoice_info_br_style          = $data->bold_right_invoice_info_br_style ; 
        $printerContentTemplate->bold_right_invoice_info_br_color          = $data->bold_right_invoice_info_br_color ; 
        $printerContentTemplate->bold_right_invoice_info_text_align        = $data->bold_right_invoice_info_text_align ; 
        $printerContentTemplate->bold_left_invoice_info_customer_number    = ($data->bold_left_invoice_info_customer_number)?true:false ; 
        $printerContentTemplate->bold_left_invoice_info_customer_address   = ($data->bold_left_invoice_info_customer_address)?true:false ; 
        $printerContentTemplate->bold_left_invoice_info_customer_mobile    = ($data->bold_left_invoice_info_customer_mobile)?true:false ; 
        $printerContentTemplate->bold_left_invoice_info_customer_tax       = ($data->bold_left_invoice_info_customer_tax)?true:false ; 
        $printerContentTemplate->bold_left_invoice_info_number             = ($data->bold_left_invoice_info_number)?true:false ; 
        $printerContentTemplate->bold_left_invoice_info_project            = ($data->bold_left_invoice_info_project)?true:false ; 
        $printerContentTemplate->bold_left_invoice_info_date               = ($data->bold_left_invoice_info_date)?true:false ; 
        $printerContentTemplate->currency_in_row                           = ($data->currency_in_row)?true:false ; 
        $printerContentTemplate->if_discount_zero                          = ($data->if_discount_zero)?true:false ; 
        $printerContentTemplate->bill_invoice_info_down_vat                = ($data->bill_invoice_info_down_vat)?true:false ; 
        $printerContentTemplate->bill_invoice_info_down_subtotal           = ($data->bill_invoice_info_down_subtotal)?true:false ; 
        $printerContentTemplate->bill_invoice_info_down_discount           = ($data->bill_invoice_info_down_discount)?true:false ; 
        $printerContentTemplate->bill_invoice_info_down_subtotal_after_dis = ($data->bill_invoice_info_down_subtotal_after_dis)?true:false ; 
        $printerContentTemplate->class_width_left                          = $data->class_width_left ; 
        $printerContentTemplate->repeat_content_top                        = ($data->repeat_content_top)?true:false ; 
        $printerContentTemplate->class_width_right                         = $data->class_width_right ; 
        $printerContentTemplate->bold_left_invoice_info                    = $data->bold_left_invoice_info ; 
        $printerContentTemplate->bold_left_invoice_info_br_width           = $data->bold_left_invoice_info_br_width ; 
        $printerContentTemplate->bold_left_invoice_info_br_style           = $data->bold_left_invoice_info_br_style ; 
        $printerContentTemplate->bold_left_invoice_info_br_color           = $data->bold_left_invoice_info_br_color ; 
        $printerContentTemplate->bold_left_invoice_info_text_align         = $data->bold_left_invoice_info_text_align ; 
        
        $printerContentTemplate->invoice_no                                = $data->invoice_no ; 
        $printerContentTemplate->project_no                                = $data->project_no ; 
        $printerContentTemplate->date_name                                 = $data->date_name ; 
        $printerContentTemplate->customer_name                             = $data->customer_no ; 
        $printerContentTemplate->address_name                              = $data->address_name ; 
        $printerContentTemplate->mobile_name                               = $data->mobile_name ; 
        $printerContentTemplate->show_customer_signature                   = ($data->show_customer_signature)?true:false; 
        $printerContentTemplate->show_quotation_terms                      = ($data->show_quotation_terms)?true:false;
        $printerContentTemplate->tax_name                                  = $data->tax_name ; 

        $printerContentTemplate->save();
        // ..... footer 
        $printerFooterTemplate                                    =  new PrinterFooterTemplate();
        $printerFooterTemplate->printer_template_id               =  $printerTemplate->id;
        $printerFooterTemplate->footer_view                       =  ($data->footer_view)?true:false;
        $printerFooterTemplate->style_footer                      =  $data->style_footer;
        $printerFooterTemplate->footer_width                      =  $data->footer_width;
        $printerFooterTemplate->footer_style_letter               =  $data->footer_style_letter;
        $printerFooterTemplate->footer_table_width                =  $data->footer_table_width;
        $printerFooterTemplate->footer_table_color                =  $data->footer_table_color;
        $printerFooterTemplate->footer_table_radius               =  $data->footer_table_radius;
        $printerFooterTemplate->align_text_footer                 =  $data->align_text_footer;
        $printerFooterTemplate->footer_font_size                  =  $data->footer_font_size;
        $printerFooterTemplate->footer_font_weight                =  $data->footer_font_weight;
        $printerFooterTemplate->footer_border_width               =  $data->footer_border_width;
        $printerFooterTemplate->footer_border_style               =  $data->footer_border_style;
        $printerFooterTemplate->footer_border_color               =  $data->footer_border_color;
        $printerFooterTemplate->footer_padding_left               =  $data->footer_padding_left;
        $printerFooterTemplate->footer_padding_top                =  $data->footer_padding_top;
        $printerFooterTemplate->footer_padding_bottom             =  $data->footer_padding_bottom;
        $printerFooterTemplate->footer_padding_right              =  $data->footer_padding_right;
        $printerFooterTemplate->footer_position                   =  $data->footer_position;
        $printerFooterTemplate->footer_top                        =  $data->footer_top;
        $printerFooterTemplate->footer_bottom                     =  $data->footer_bottom;
        $printerFooterTemplate->footer_left                       =  $data->footer_left;
        $printerFooterTemplate->footer_right                      =  $data->footer_right;
        $printerFooterTemplate->footer_box_width                  =  $data->footer_box_width;
        $printerFooterTemplate->footer_box_border_style           =  $data->footer_box_border_style;
        $printerFooterTemplate->footer_box_border_width           =  $data->footer_box_border_width;
        $printerFooterTemplate->footer_box_background             =  $data->footer_box_background;
        $printerFooterTemplate->footer_box_border_color           =  $data->footer_box_border_color;
        $printerFooterTemplate->footer_box_border_radius          =  $data->footer_box_border_radius;
        $printerFooterTemplate->footer_image_view                 =  ($data->footer_image_view)?true:false;
        $printerFooterTemplate->align_image_footer                =  $data->align_image_footer;
        $printerFooterTemplate->position_img_footer               =  $data->position_img_footer;
        $printerFooterTemplate->footer_image_width                =  $data->footer_image_width;
        $printerFooterTemplate->footer_image_height               =  $data->footer_image_height;
        $printerFooterTemplate->footer_image_border_width         =  $data->footer_image_border_width;
        $printerFooterTemplate->footer_image_border_color         =  $data->footer_image_border_color;
        $printerFooterTemplate->footer_image_border_style         =  $data->footer_image_border_style;
        $printerFooterTemplate->footer_image_border_radius        =  $data->footer_image_border_radius;
        $printerFooterTemplate->footer_image_box_width            =  $data->footer_image_box_width;
        $printerFooterTemplate->footer_image_box_height           =  $data->footer_image_box_height;
        $printerFooterTemplate->footer_image_box_margin           =  $data->footer_image_box_margin;
        $printerFooterTemplate->footer_box_image_background       =  $data->footer_box_image_background;
        $printerFooterTemplate->footer_box_image_color            =  $data->footer_box_image_color;
        $printerFooterTemplate->position_box_footer_align         =  $data->position_box_footer_align;
        $printerFooterTemplate->footer_image_box_background       =  $data->footer_image_box_background;
        $printerFooterTemplate->footer_image_box_border_width     =  $data->footer_image_box_border_width;
        $printerFooterTemplate->footer_image_box_border_style     =  $data->footer_image_box_border_style;
        $printerFooterTemplate->footer_image_box_border_color     =  $data->footer_image_box_border_color;
        $printerFooterTemplate->footer_image_box_border_radius    =  $data->footer_image_box_border_radius;
        $printerFooterTemplate->footer_other_view                 =  ($data->footer_other_view)?true:false;
        $printerFooterTemplate->align_other_footer                =  $data->align_other_footer;
        $printerFooterTemplate->other_background_footer           =  $data->other_background_footer;
        $printerFooterTemplate->footer_other_width                =  $data->footer_other_width;
        $printerFooterTemplate->footer_other_border_radius        =  $data->footer_other_border_radius;
        $printerFooterTemplate->footer_other_border_width         =  $data->footer_other_border_width;
        $printerFooterTemplate->footer_other_border_style         =  $data->footer_other_border_style;
        $printerFooterTemplate->footer_other_border_color         =  $data->footer_other_border_color;
        $printerFooterTemplate->footer_other_position             =  $data->footer_other_position;
        $printerFooterTemplate->footer_other_top                  =  $data->footer_other_top;
        $printerFooterTemplate->footer_other_left                 =  $data->footer_other_left;
        $printerFooterTemplate->footer_other_right                =  $data->footer_other_right;
        $printerFooterTemplate->footer_other_bottom               =  $data->footer_other_bottom;
        $printerFooterTemplate->footer_tax_align                  =  $data->footer_tax_align;
        $printerFooterTemplate->footer_tax_font_size              =  $data->footer_tax_font_size;
        $printerFooterTemplate->footer_tax_width                  =  $data->footer_tax_width;
        $printerFooterTemplate->footer_tax_letter                 =  $data->footer_tax_letter;
        $printerFooterTemplate->footer_tax_border_width           =  $data->footer_tax_border_width;
        $printerFooterTemplate->footer_tax_border_style           =  $data->footer_tax_border_style;
        $printerFooterTemplate->footer_tax_border_color           =  $data->footer_tax_border_color;
        $printerFooterTemplate->footer_tax_padding_top            =  $data->footer_tax_padding_top;
        $printerFooterTemplate->footer_tax_padding_left           =  $data->footer_tax_padding_left;
        $printerFooterTemplate->footer_tax_padding_right          =  $data->footer_tax_padding_right;
        $printerFooterTemplate->footer_tax_padding_bottom         =  $data->footer_tax_padding_bottom;
        $printerFooterTemplate->footer_tax_position               =  $data->footer_tax_position;
        $printerFooterTemplate->footer_tax_top                    =  $data->footer_tax_top;
        $printerFooterTemplate->footer_tax_bottom                 =  $data->footer_tax_bottom;
        $printerFooterTemplate->footer_tax_left                   =  $data->footer_tax_left;
        $printerFooterTemplate->footer_tax_right                  =  $data->footer_tax_right;
        $printerFooterTemplate->footer_address_align              =  $data->footer_address_align;  
        $printerFooterTemplate->footer_address_font_size          =  $data->footer_address_font_size;
        $printerFooterTemplate->footer_address_width              =  $data->footer_address_width;
        $printerFooterTemplate->footer_address_letter             =  $data->footer_address_letter;
        $printerFooterTemplate->footer_address_border_width       =  $data->footer_address_border_width;
        $printerFooterTemplate->footer_address_border_style       =  $data->footer_address_border_style;
        $printerFooterTemplate->footer_address_border_color       =  $data->footer_address_border_color;
        $printerFooterTemplate->footer_address_padding_top        =  $data->footer_address_padding_top;
        $printerFooterTemplate->footer_address_padding_left       =  $data->footer_address_padding_left;
        $printerFooterTemplate->footer_address_padding_right      =  $data->footer_address_padding_right;
        $printerFooterTemplate->footer_address_padding_bottom     =  $data->footer_address_padding_bottom;
        $printerFooterTemplate->footer_address_position           =  $data->footer_address_position;
        $printerFooterTemplate->footer_address_top                =  $data->footer_address_top;
        $printerFooterTemplate->footer_address_bottom             =  $data->footer_address_bottom;
        $printerFooterTemplate->footer_address_left               =  $data->footer_address_left;
        $printerFooterTemplate->footer_address_right              =  $data->footer_address_right;
        $printerFooterTemplate->footer_bill_align                 =  $data->footer_bill_align;
        $printerFooterTemplate->footer_bill_font_size             =  $data->footer_bill_font_size;
        $printerFooterTemplate->footer_bill_width                 =  $data->footer_bill_width;
        $printerFooterTemplate->footer_bill_letter                =  $data->footer_bill_letter;
        $printerFooterTemplate->footer_bill_border_width          =  $data->footer_bill_border_width;
        $printerFooterTemplate->footer_bill_border_style          =  $data->footer_bill_border_style;
        $printerFooterTemplate->footer_bill_border_color          =  $data->footer_bill_border_color;
        $printerFooterTemplate->footer_bill_padding_top           =  $data->footer_bill_padding_top;
        $printerFooterTemplate->footer_bill_padding_left          =  $data->footer_bill_padding_left;
        $printerFooterTemplate->footer_bill_padding_right         =  $data->footer_bill_padding_right;
        $printerFooterTemplate->footer_bill_padding_bottom        =  $data->footer_bill_padding_bottom;
        $printerFooterTemplate->footer_bill_position              =  $data->footer_bill_position;
        $printerFooterTemplate->footer_bill_top                   =  $data->footer_bill_top;
        $printerFooterTemplate->footer_bill_bottom                =  $data->footer_bill_bottom;
        $printerFooterTemplate->footer_bill_left                  =  $data->footer_bill_left;
        $printerFooterTemplate->footer_bill_right                 =  $data->footer_bill_right;
        $printerFooterTemplate->footer_line_view                  =  ($data->footer_line_view)?true:false;
        $printerFooterTemplate->footer_line_height                =  $data->footer_line_height;
        $printerFooterTemplate->footer_line_width                 =  $data->footer_line_width;
        $printerFooterTemplate->footer_line_color                 =  $data->footer_line_color;
        $printerFooterTemplate->footer_line_margin_top            =  $data->footer_line_margin_top;
        $printerFooterTemplate->footer_line_margin_bottom         =  $data->footer_line_margin_bottom;
        $printerFooterTemplate->footer_line_radius                =  $data->footer_line_radius;
        $printerFooterTemplate->footer_line_border_width          =  $data->footer_line_border_width;
        $printerFooterTemplate->footer_line_border_style          =  $data->footer_line_border_style;
        $printerFooterTemplate->footer_line_border_color          =  $data->footer_line_border_color;
        $printerFooterTemplate->page_number_view                  =  ($data->page_number_view!=null)?true:false;
        $printerFooterTemplate->save();
        PrinterTemplateContain::storeTemplateContain($data,$printerTemplate->id,$request);
       
    }
    // update
    public static function updateTemplate($data,$id,$request){
        $size  = $data->only("Paper-size","Form-type","Pattern-type","Voucher-type","Cheque-type");
        $type  = "";
        if($size["Form-type"] == "Sale"){
            $type  = $size["Pattern-type"];
        }elseif($size["Form-type"] == "Return_Sale"){
            $type  = $size["Pattern-type"];
        }elseif($size["Form-type"] == "Voucher"){
            $type  = $size["Voucher-type"];
        }elseif($size["Form-type"] == "Cheques"){
            $type  = $size["Cheque-type"];
        }else{
            $type  = null;
        }
        $printerTemplate                                        = PrinterTemplate::find($id);
        if(!empty($printerTemplate)){

            // header
            $printerTemplate->name_template                     =  $data->name_template;
            $printerTemplate->page_size                         =  $size["Paper-size"];
            $printerTemplate->Form_type                         =  $size["Form-type"];
            $printerTemplate->type                              =  $type;
            $printerTemplate->header_view                       =  ($data->header_view)?true:false;
            $printerTemplate->style_header                      =  $data->style_header;
            $printerTemplate->header_width                      =  $data->header_width;
            $printerTemplate->header_style_letter               =  $data->header_style_letter;
            $printerTemplate->header_table_width                =  $data->header_table_width;
            $printerTemplate->header_table_color                =  $data->header_table_color;
            $printerTemplate->header_table_radius               =  $data->header_table_radius;
            $printerTemplate->align_text_header                 =  $data->align_text_header;
            $printerTemplate->header_font_size                  =  $data->header_font_size;
            $printerTemplate->header_font_weight                =  $data->header_font_weight;
            $printerTemplate->header_border_width               =  $data->header_border_width;
            $printerTemplate->header_border_style               =  $data->header_border_style;
            $printerTemplate->header_border_color               =  $data->header_border_color;
            $printerTemplate->header_padding_left               =  $data->header_padding_left;
            $printerTemplate->header_padding_top                =  $data->header_padding_top;
            $printerTemplate->header_padding_right              =  $data->header_padding_right;
            $printerTemplate->header_padding_bottom             =  $data->header_padding_bottom;
            $printerTemplate->header_position                   =  $data->header_position;
            $printerTemplate->header_top                        =  $data->header_top;
            $printerTemplate->header_bottom                     =  $data->header_bottom;
            $printerTemplate->header_left                       =  $data->header_left;
            $printerTemplate->header_right                      =  $data->header_right;
            $printerTemplate->header_box_width                  =  $data->header_box_width;
            $printerTemplate->header_box_border_style           =  $data->header_box_border_style;
            $printerTemplate->header_box_border_width           =  $data->header_box_border_width;
            $printerTemplate->header_box_background             =  $data->header_box_background;
            $printerTemplate->header_box_border_color           =  $data->header_box_border_color;
            $printerTemplate->header_box_border_radius          =  $data->header_box_border_radius;
            $printerTemplate->header_image_view                 =  ($data->header_image_view)?true:false;
            $printerTemplate->align_image_header                =  $data->align_image_header;
            $printerTemplate->position_img_header               =  $data->position_img_header;
            $printerTemplate->header_image_width                =  $data->header_image_width;
            $printerTemplate->header_image_height               =  $data->header_image_height;
            $printerTemplate->header_image_border_width         =  $data->header_image_border_width;
            $printerTemplate->header_image_border_color         =  $data->header_image_border_color;
            $printerTemplate->header_image_border_style         =  $data->header_image_border_style;
            $printerTemplate->header_image_border_radius        =  $data->header_image_border_radius;
            $printerTemplate->header_image_box_width            =  $data->header_image_box_width;
            $printerTemplate->header_image_box_height           =  $data->header_image_box_height;
            $printerTemplate->header_image_box_margin           =  $data->header_image_box_margin;
            $printerTemplate->header_box_image_background       =  $data->header_box_image_background;
            $printerTemplate->header_box_image_color            =  $data->header_box_image_color;
            $printerTemplate->position_box_header_align         =  $data->position_box_header_align;
            $printerTemplate->header_image_box_background       =  $data->header_image_box_background;
            $printerTemplate->header_image_box_border_width     =  $data->header_image_box_border_width;
            $printerTemplate->header_image_box_border_style     =  $data->header_image_box_border_style;
            $printerTemplate->header_image_box_border_color     =  $data->header_image_box_border_color;
            $printerTemplate->header_image_box_border_radius    =  $data->header_image_box_border_radius;
            $printerTemplate->header_other_view                 =  ($data->header_other_view)?true:false;
            $printerTemplate->align_other_header                =  $data->align_other_header;
            $printerTemplate->other_background_header           =  $data->other_background_header;
            $printerTemplate->header_other_width                =  $data->header_other_width;
            $printerTemplate->header_other_border_radius        =  $data->header_other_border_radius;
            $printerTemplate->header_other_border_width         =  $data->header_other_border_width;
            $printerTemplate->header_other_border_style         =  $data->header_other_border_style;
            $printerTemplate->header_other_border_color         =  $data->header_other_border_color;
            $printerTemplate->header_other_position             =  $data->header_other_position;
            $printerTemplate->header_other_top                  =  $data->header_other_top;
            $printerTemplate->header_other_left                 =  $data->header_other_left;
            $printerTemplate->header_other_right                =  $data->header_other_right;
            $printerTemplate->header_other_bottom               =  $data->header_other_bottom;
            $printerTemplate->header_tax_align                  =  $data->header_tax_align;
            $printerTemplate->header_tax_font_size              =  $data->header_tax_font_size;
            $printerTemplate->header_tax_width                  =  $data->header_tax_width;
            $printerTemplate->header_tax_letter                 =  $data->header_tax_letter;
            $printerTemplate->header_tax_border_width           =  $data->header_tax_border_width;
            $printerTemplate->header_tax_border_style           =  $data->header_tax_border_style;
            $printerTemplate->header_tax_border_color           =  $data->header_tax_border_color;
            $printerTemplate->header_tax_padding_top            =  $data->header_tax_padding_top;
            $printerTemplate->header_tax_padding_left           =  $data->header_tax_padding_left;
            $printerTemplate->header_tax_padding_right          =  $data->header_tax_padding_right;
            $printerTemplate->header_tax_padding_bottom         =  $data->header_tax_padding_bottom;
            $printerTemplate->header_tax_position               =  $data->header_tax_position;
            $printerTemplate->header_tax_top                    =  $data->header_tax_top;
            $printerTemplate->header_tax_bottom                 =  $data->header_tax_bottom;
            $printerTemplate->header_tax_left                   =  $data->header_tax_left;
            $printerTemplate->header_tax_right                  =  $data->header_tax_right;
            $printerTemplate->header_address_align              =  $data->header_address_align;
            $printerTemplate->header_address_font_size          =  $data->header_address_font_size;
            $printerTemplate->header_address_width              =  $data->header_address_width;
            $printerTemplate->header_address_letter             =  $data->header_address_letter;
            $printerTemplate->header_address_border_width       =  $data->header_address_border_width;
            $printerTemplate->header_address_border_style       =  $data->header_address_border_style;
            $printerTemplate->header_address_border_color       =  $data->header_address_border_color;
            $printerTemplate->header_address_padding_top        =  $data->header_address_padding_top;
            $printerTemplate->header_address_padding_left       =  $data->header_address_padding_left;
            $printerTemplate->header_address_padding_right      =  $data->header_address_padding_right;
            $printerTemplate->header_address_padding_bottom     =  $data->header_address_padding_bottom;
            $printerTemplate->header_address_position           =  $data->header_address_position;
            $printerTemplate->header_address_top                =  $data->header_address_top;
            $printerTemplate->header_address_bottom             =  $data->header_address_bottom;
            $printerTemplate->header_address_left               =  $data->header_address_left;
            $printerTemplate->header_address_right              =  $data->header_address_right;
            $printerTemplate->header_bill_align                 =  $data->header_bill_align;
            $printerTemplate->header_bill_font_size             =  $data->header_bill_font_size;
            $printerTemplate->header_bill_width                 =  $data->header_bill_width;
            $printerTemplate->header_bill_letter                =  $data->header_bill_letter;
            $printerTemplate->header_bill_border_width          =  $data->header_bill_border_width;
            $printerTemplate->header_bill_border_style          =  $data->header_bill_border_style;
            $printerTemplate->header_bill_border_color          =  $data->header_bill_border_color;
            $printerTemplate->header_bill_padding_top           =  $data->header_bill_padding_top;
            $printerTemplate->header_bill_padding_left          =  $data->header_bill_padding_left;
            $printerTemplate->header_bill_padding_right         =  $data->header_bill_padding_right;
            $printerTemplate->header_bill_padding_bottom        =  $data->header_bill_padding_bottom;
            $printerTemplate->header_bill_position              =  $data->header_bill_position;
            $printerTemplate->header_bill_top                   =  $data->header_bill_top;
            $printerTemplate->header_bill_bottom                =  $data->header_bill_bottom;
            $printerTemplate->header_bill_left                  =  $data->header_bill_left;
            $printerTemplate->header_bill_right                 =  $data->header_bill_right;
            $printerTemplate->header_line_view                  =  ($data->header_line_view)?true:false;
            $printerTemplate->header_line_height                =  $data->header_line_height;
            $printerTemplate->header_line_width                 =  $data->header_line_width;
            $printerTemplate->header_line_color                 =  $data->header_line_color;
            $printerTemplate->header_line_margin_top            =  $data->header_line_margin_top;
            $printerTemplate->header_line_radius                =  $data->header_line_radius;
            $printerTemplate->header_line_border_width          =  $data->header_line_border_width;
            $printerTemplate->header_line_border_style          =  $data->header_line_border_style;
            $printerTemplate->header_line_border_color          =  $data->header_line_border_color;
            $printerTemplate->update();
            
            // content
            $printerContentTemplate                                    = PrinterContentTemplate::where("printer_template_id",$id)->first();
            $printerContentTemplate->printer_template_id               =  $printerTemplate->id;
            $printerContentTemplate->top_table_section                 =  ($data->top_table_section)?true:false;
            $printerContentTemplate->top_table_margin_bottom           =  $data->top_table_margin_bottom;
            $printerContentTemplate->top_table_width                   =  $data->top_table_width;
            $printerContentTemplate->top_table_td_border_width         =  $data->top_table_td_border_width;
            $printerContentTemplate->top_table_td_border_style         =  $data->top_table_td_border_style;
            $printerContentTemplate->top_table_td_border_color         =  $data->top_table_td_border_color;
            $printerContentTemplate->left_top_table_width              =  $data->left_top_table_width;
            $printerContentTemplate->left_top_table_text_align         =  $data->left_top_table_text_align;
            $printerContentTemplate->left_top_table_font_size          =  $data->left_top_table_font_size;
            $printerContentTemplate->right_top_table_width             =  $data->right_top_table_width;
            $printerContentTemplate->right_top_table_text_align        =  $data->right_top_table_text_align;
            $printerContentTemplate->right_top_table_font_size         =  $data->right_top_table_font_size;
            $printerContentTemplate->top_table_border_width            =  $data->top_table_border_width;
            $printerContentTemplate->top_table_border_style            =  $data->top_table_border_style;
            $printerContentTemplate->top_table_border_color            =  $data->top_table_border_color;
            $printerContentTemplate->content_table_section             =  ($data->content_table_section)?true:false;
            $printerContentTemplate->content_table_width               =  $data->content_table_width;
            $printerContentTemplate->content_width                     =  $data->content_width;
            $printerContentTemplate->content_table_border_radius       =  $data->content_table_border_radius;
            $printerContentTemplate->footer_table                      =  $data->footer_table;  
            $printerContentTemplate->content_table_th_font_size        =  $data->content_table_th_font_size;
            $printerContentTemplate->content_table_th_border_width     =  $data->content_table_th_border_width;
            $printerContentTemplate->content_table_th_text_align       =  $data->content_table_th_text_align;
            $printerContentTemplate->content_table_th_border_style     =  $data->content_table_th_border_style;
            $printerContentTemplate->content_table_th_padding          =  $data->content_table_th_padding;
            $printerContentTemplate->content_table_th_border_color     =  $data->content_table_th_border_color;
            $printerContentTemplate->content_table_td_font_size        =  $data->content_table_td_font_size;
            $printerContentTemplate->content_table_td_border_width     =  $data->content_table_td_border_width;
            $printerContentTemplate->content_table_td_text_align       =  $data->content_table_td_text_align;
            $printerContentTemplate->content_table_td_border_style     =  $data->content_table_td_border_style;
            $printerContentTemplate->content_table_td_padding          =  $data->content_table_td_padding;
            $printerContentTemplate->content_table_td_border_color     =  $data->content_table_td_border_color;
            $printerContentTemplate->table_th_no                       =  $data->table_th_no;
            $printerContentTemplate->content_table_width_no            =  $data->content_table_width_no;
            $printerContentTemplate->content_table_font_weight_no      =  $data->content_table_font_weight_no;
            $printerContentTemplate->content_table_td_no_font_size     =  $data->content_table_td_no_font_size;
            $printerContentTemplate->content_table_td_no_text_align    =  $data->content_table_td_no_text_align;
            $printerContentTemplate->table_th_name                     =  $data->table_th_name;
            $printerContentTemplate->content_table_width_name          =  $data->content_table_width_name;
            $printerContentTemplate->content_table_font_weight_name    =  $data->content_table_font_weight_name;
            $printerContentTemplate->content_table_font_size_name      =  $data->content_table_font_size_name;
            $printerContentTemplate->content_table_text_align_name     =  $data->content_table_text_align_name;

            $printerContentTemplate->table_th_qty                      =  $data->table_th_qty;
            $printerContentTemplate->content_table_width_qty           =  $data->content_table_width_qty;
            $printerContentTemplate->content_table_font_weight_qty     =  $data->content_table_font_weight_qty;
            $printerContentTemplate->content_table_td_qty_font_size    =  $data->content_table_td_qty_font_size;
            $printerContentTemplate->content_table_td_qty_text_align   =  $data->content_table_td_qty_text_align;

            $printerContentTemplate->table_th_code                      =  $data->table_th_code;
            $printerContentTemplate->content_table_width_code           =  $data->content_table_width_code;
            $printerContentTemplate->content_table_font_weight_code     =  $data->content_table_font_weight_code;
            $printerContentTemplate->content_table_td_code_font_size    =  $data->content_table_td_code_font_size;
            $printerContentTemplate->content_table_td_code_text_align   =  $data->content_table_td_code_text_align;

            $printerContentTemplate->table_th_img                       =  $data->table_th_img;
            $printerContentTemplate->content_table_width_img            =  $data->content_table_width_img;
            $printerContentTemplate->content_table_font_weight_img      =  $data->content_table_font_weight_img;
            $printerContentTemplate->content_table_td_img_font_size     =  $data->content_table_td_img_font_size;
            $printerContentTemplate->content_table_td_img_text_align    =  $data->content_table_td_img_text_align;

            $printerContentTemplate->table_th_discount                      =  $data->table_th_discount;
            $printerContentTemplate->content_table_width_discount           =  $data->content_table_width_discount;
            $printerContentTemplate->content_table_font_weight_discount     =  $data->content_table_font_weight_discount;
            $printerContentTemplate->content_table_td_discount_font_size    =  $data->content_table_td_discount_font_size;
            $printerContentTemplate->content_table_td_discount_text_align   =  $data->content_table_td_discount_text_align;
            
            $printerContentTemplate->table_th_subtotal                      =  $data->table_th_subtotal;
            $printerContentTemplate->content_table_width_subtotal           =  $data->content_table_width_subtotal;
            $printerContentTemplate->content_table_font_weight_subtotal     =  $data->content_table_font_weight_subtotal;
            $printerContentTemplate->content_table_td_subtotal_font_size    =  $data->content_table_td_subtotal_font_size;
            $printerContentTemplate->content_table_td_subtotal_text_align   =  $data->content_table_td_subtotal_text_align;
    

            $printerContentTemplate->table_th_price                    =  $data->table_th_price;
            $printerContentTemplate->content_table_width_price         =  $data->content_table_width_price;
            $printerContentTemplate->content_table_font_weight_price   =  $data->content_table_font_weight_price;
            $printerContentTemplate->content_table_td_price_font_size  =  $data->content_table_td_price_font_size;
            $printerContentTemplate->content_table_td_price_text_align =  $data->content_table_td_price_text_align;

            $printerContentTemplate->table_th_price_bdi                    =  $data->table_th_price_bdi;
            $printerContentTemplate->content_table_width_price_bdi         =  $data->content_table_width_price_bdi;
            $printerContentTemplate->content_table_font_weight_price_bdi   =  $data->content_table_font_weight_price_bdi;
            $printerContentTemplate->content_table_td_price_bdi_font_size  =  $data->content_table_td_price_bdi_font_size;
            $printerContentTemplate->content_table_td_price_bdi_text_align =  $data->content_table_td_price_bdi_text_align;
    
            $printerContentTemplate->table_th_price_ade                    =  $data->table_th_price_ade;
            $printerContentTemplate->content_table_width_price_ade         =  $data->content_table_width_price_ade;
            $printerContentTemplate->content_table_font_weight_price_ade   =  $data->content_table_font_weight_price_ade;
            $printerContentTemplate->content_table_td_price_ade_font_size  =  $data->content_table_td_price_ade_font_size;
            $printerContentTemplate->content_table_td_price_ade_text_align =  $data->content_table_td_price_ade_text_align;
    
            $printerContentTemplate->table_th_price_adi                    =  $data->table_th_price_adi;
            $printerContentTemplate->content_table_width_price_adi         =  $data->content_table_width_price_adi;
            $printerContentTemplate->content_table_font_weight_price_adi   =  $data->content_table_font_weight_price_adi;
            $printerContentTemplate->content_table_td_price_adi_font_size  =  $data->content_table_td_price_adi_font_size;
            $printerContentTemplate->content_table_td_price_adi_text_align =  $data->content_table_td_price_adi_text_align;

            $printerContentTemplate->bottom_table_section              =  ($data->bottom_table_section)?true:false;
            $printerContentTemplate->left_bottom_table_width           =  $data->left_bottom_table_width;
            $printerContentTemplate->left_bottom_table_td_bor_width    =  $data->left_bottom_table_td_bor_width;
            $printerContentTemplate->left_bottom_table_text_align      =  $data->left_bottom_table_text_align;
            $printerContentTemplate->left_bottom_table_td_bor_style    =  $data->left_bottom_table_td_bor_style;
            $printerContentTemplate->left_bottom_table_font_size       =  $data->left_bottom_table_font_size;
            $printerContentTemplate->left_bottom_table_td_bor_color    =  $data->left_bottom_table_td_bor_color;
            $printerContentTemplate->right_bottom_table_width          =  $data->right_bottom_table_width;
            $printerContentTemplate->right_bottom_table_td_bor_width   =  $data->right_bottom_table_td_bor_width;
            $printerContentTemplate->right_bottom_table_text_align     =  $data->right_bottom_table_text_align;
            $printerContentTemplate->right_bottom_table_td_bor_style   =  $data->right_bottom_table_td_bor_style;
            $printerContentTemplate->right_bottom_table_font_size      =  $data->right_bottom_table_font_size;
            $printerContentTemplate->right_bottom_table_td_bor_color   =  $data->right_bottom_table_td_bor_color;
            $printerContentTemplate->bill_table_info_width             =  $data->bill_table_info_width;
            $printerContentTemplate->bill_table_margin_bottom          =  $data->bill_table_margin_bottom;
            $printerContentTemplate->bill_table_info_border_width      =  $data->bill_table_info_border_width;
            $printerContentTemplate->bill_table_margin_top             =  $data->bill_table_margin_top;
            $printerContentTemplate->bill_table_info_border_style      =  $data->bill_table_info_border_style;
            $printerContentTemplate->bill_table_info_border_color      =  $data->bill_table_info_border_color;
            $printerContentTemplate->bill_table_border_width           =  $data->bill_table_border_width;
            $printerContentTemplate->bill_table_border_style           =  $data->bill_table_border_style;
            $printerContentTemplate->bill_table_border_color           =  $data->bill_table_border_color;
            $printerContentTemplate->bill_table_left_td_width          =  $data->bill_table_left_td_width;
            $printerContentTemplate->bill_table_left_td_font_size      =  $data->bill_table_left_td_font_size;
            $printerContentTemplate->bill_table_left_td_weight         =  $data->bill_table_left_td_weight;
            $printerContentTemplate->bill_table_left_td_text_align     =  $data->bill_table_left_td_text_align;
            $printerContentTemplate->bill_table_left_td_border_width   =  $data->bill_table_left_td_border_width;
            $printerContentTemplate->bill_table_left_td_padding_left   =  $data->bill_table_left_td_padding_left;
            $printerContentTemplate->bill_table_left_td_border_style   =  $data->bill_table_left_td_border_style;
            $printerContentTemplate->bill_table_left_td_border_color   =  $data->bill_table_left_td_border_color;
            $printerContentTemplate->bill_table_right_td_width         =  $data->bill_table_right_td_width;
            $printerContentTemplate->bill_table_right_td_font_size     =  $data->bill_table_right_td_font_size;
            $printerContentTemplate->bill_table_right_td_weight        =  $data->bill_table_right_td_weight;
            $printerContentTemplate->bill_table_right_td_text_align    =  $data->bill_table_right_td_text_align;
            $printerContentTemplate->bill_table_right_td_border_width  =  $data->bill_table_right_td_border_width;
            $printerContentTemplate->bill_table_right_td_padding_left  =  $data->bill_table_right_td_padding_left;
            $printerContentTemplate->bill_table_right_td_border_style  =  $data->bill_table_right_td_border_style;
            $printerContentTemplate->bill_table_right_td_border_color  =  $data->bill_table_right_td_border_color;
            $printerContentTemplate->line_bill_table_width             =  $data->line_bill_table_width;
            $printerContentTemplate->line_bill_table_height            =  $data->line_bill_table_height;
            $printerContentTemplate->line_bill_table_color             =  $data->line_bill_table_color;
            $printerContentTemplate->line_bill_table_border_width      =  $data->line_bill_table_border_width;
            $printerContentTemplate->line_bill_table_border_style      =  $data->line_bill_table_border_style;
            $printerContentTemplate->line_bill_table_border_color      =  $data->line_bill_table_border_color;
            $printerContentTemplate->line_bill_table_td_margin_left    =  $data->line_bill_table_td_margin_left;

            $printerContentTemplate->table_th_no_named                 =  $data->table_th_no_named;
            $printerContentTemplate->table_th_code_named               =  $data->table_th_code_named;
            $printerContentTemplate->table_th_name_named               =  $data->table_th_name_named;
            $printerContentTemplate->table_th_img_named                =  $data->table_th_img_named;
            $printerContentTemplate->table_th_qty_named                =  $data->table_th_qty_named;
            $printerContentTemplate->table_th_price_named              =  $data->table_th_price_named;
            $printerContentTemplate->table_th_price_bdi_named          =  $data->table_th_price_bdi_named;
            $printerContentTemplate->table_th_discount_named           =  $data->table_th_discount_named;
            $printerContentTemplate->table_th_price_ade_named          =  $data->table_th_price_ade_named;
            $printerContentTemplate->table_th_price_adi_named          =  $data->table_th_price_adi_named;
            $printerContentTemplate->table_th_subtotal_named           =  $data->table_th_subtotal_named;

            $printerContentTemplate->left_invoice_info                         = $data->left_invoice_info ; 
            $printerContentTemplate->color_invoice_info                        = $data->color_invoice_info ; 
            $printerContentTemplate->right_invoice_info                        = $data->right_invoice_info ; 
            $printerContentTemplate->padding_invoice_info                      = $data->padding_invoice_info ; 
            $printerContentTemplate->background_color_invoice_info             = $data->background_color_invoice_info ; 
            $printerContentTemplate->class_width_left_right                    = $data->class_width_left_right ; 
            $printerContentTemplate->class_width_right_right                   = $data->class_width_right_right ; 
            $printerContentTemplate->bold_right_invoice_info                   = $data->bold_right_invoice_info ; 
            $printerContentTemplate->bold_right_invoice_info_br_width          = $data->bold_right_invoice_info_br_width ; 
            $printerContentTemplate->bold_right_invoice_info_br_style          = $data->bold_right_invoice_info_br_style ; 
            $printerContentTemplate->bold_right_invoice_info_br_color          = $data->bold_right_invoice_info_br_color ; 
            $printerContentTemplate->bold_right_invoice_info_text_align        = $data->bold_right_invoice_info_text_align ; 
            $printerContentTemplate->bold_left_invoice_info_customer_number    = ($data->bold_left_invoice_info_customer_number)?true:false; 
            $printerContentTemplate->bold_left_invoice_info_customer_address   = ($data->bold_left_invoice_info_customer_address)?true:false; 
            $printerContentTemplate->bold_left_invoice_info_customer_mobile    = ($data->bold_left_invoice_info_customer_mobile)?true:false; 
            $printerContentTemplate->bold_left_invoice_info_customer_tax       = ($data->bold_left_invoice_info_customer_tax)?true:false ; 
            $printerContentTemplate->bold_left_invoice_info_number             = ($data->bold_left_invoice_info_number)?true:false; 
            $printerContentTemplate->bold_left_invoice_info_project            = ($data->bold_left_invoice_info_project)?true:false ; 
            $printerContentTemplate->bold_left_invoice_info_date               = ($data->bold_left_invoice_info_date)?true:false; 
            $printerContentTemplate->currency_in_row                           = ($data->currency_in_row)?true:false ; 
            $printerContentTemplate->if_discount_zero                          = ($data->if_discount_zero)?true:false ; 
            $printerContentTemplate->bill_invoice_info_down_vat                = ($data->bill_invoice_info_down_vat)?true:false ; 
            $printerContentTemplate->bill_invoice_info_down_subtotal           = ($data->bill_invoice_info_down_subtotal)?true:false ; 
            $printerContentTemplate->bill_invoice_info_down_discount           = ($data->bill_invoice_info_down_discount)?true:false ; 
            $printerContentTemplate->bill_invoice_info_down_subtotal_after_dis = ($data->bill_invoice_info_down_subtotal_after_dis)?true:false ; 
            $printerContentTemplate->class_width_left                          = $data->class_width_left ; 
            $printerContentTemplate->class_width_right                         = $data->class_width_right ; 
            $printerContentTemplate->repeat_content_top                        = ($data->repeat_content_top)?true:false ; 
            $printerContentTemplate->bold_left_invoice_info                    = $data->bold_left_invoice_info ; 
            $printerContentTemplate->bold_left_invoice_info_br_width           = $data->bold_left_invoice_info_br_width ; 
            $printerContentTemplate->bold_left_invoice_info_br_style           = $data->bold_left_invoice_info_br_style ; 
            $printerContentTemplate->bold_left_invoice_info_br_color           = $data->bold_left_invoice_info_br_color ; 
            $printerContentTemplate->bold_left_invoice_info_text_align         = $data->bold_left_invoice_info_text_align ; 
            $printerContentTemplate->invoice_no                                = $data->invoice_no ; 
            $printerContentTemplate->project_no                                = $data->project_no ; 
            $printerContentTemplate->date_name                                 = $data->date_name ; 
            $printerContentTemplate->customer_name                             = $data->customer_no ; 
            $printerContentTemplate->address_name                              = $data->address_name ; 
            $printerContentTemplate->mobile_name                               = $data->mobile_name ; 
            $printerContentTemplate->show_customer_signature                   = ($data->show_customer_signature)?true:false; 
            $printerContentTemplate->show_quotation_terms                      = ($data->show_quotation_terms)?true:false;
            $printerContentTemplate->tax_name                                  = $data->tax_name ; 
            $printerContentTemplate->update();
            // footer
            $printerFooterTemplate                                    = PrinterFooterTemplate::where("printer_template_id",$id)->first();
            $printerFooterTemplate->printer_template_id               =  $printerTemplate->id;
            $printerFooterTemplate->footer_view                       =  ($data->footer_view)?true:false;
            $printerFooterTemplate->style_footer                      =  $data->style_footer;
            $printerFooterTemplate->footer_width                      =  $data->footer_width;
            $printerFooterTemplate->footer_style_letter               =  $data->footer_style_letter;
            $printerFooterTemplate->footer_table_width                =  $data->footer_table_width;
            $printerFooterTemplate->footer_table_color                =  $data->footer_table_color;
            $printerFooterTemplate->footer_table_radius               =  $data->footer_table_radius;
            $printerFooterTemplate->align_text_footer                 =  $data->align_text_footer;
            $printerFooterTemplate->footer_font_size                  =  $data->footer_font_size;
            $printerFooterTemplate->footer_font_weight                =  $data->footer_font_weight;
            $printerFooterTemplate->footer_border_width               =  $data->footer_border_width;
            $printerFooterTemplate->footer_border_style               =  $data->footer_border_style;
            $printerFooterTemplate->footer_border_color               =  $data->footer_border_color;
            $printerFooterTemplate->footer_padding_left               =  $data->footer_padding_left;
            $printerFooterTemplate->footer_padding_top                =  $data->footer_padding_top;
            $printerFooterTemplate->footer_padding_bottom             =  $data->footer_padding_bottom;
            $printerFooterTemplate->footer_padding_right              =  $data->footer_padding_right;
            $printerFooterTemplate->footer_position                   =  $data->footer_position;
            $printerFooterTemplate->footer_top                        =  $data->footer_top;
            $printerFooterTemplate->footer_bottom                     =  $data->footer_bottom;
            $printerFooterTemplate->footer_left                       =  $data->footer_left;
            $printerFooterTemplate->footer_right                      =  $data->footer_right;
            $printerFooterTemplate->footer_box_width                  =  $data->footer_box_width;
            $printerFooterTemplate->footer_box_border_style           =  $data->footer_box_border_style;
            $printerFooterTemplate->footer_box_border_width           =  $data->footer_box_border_width;
            $printerFooterTemplate->footer_box_background             =  $data->footer_box_background;
            $printerFooterTemplate->footer_box_border_color           =  $data->footer_box_border_color;
            $printerFooterTemplate->footer_box_border_radius          =  $data->footer_box_border_radius;
            $printerFooterTemplate->footer_image_view                 =  ($data->footer_image_view)?true:false;
            $printerFooterTemplate->align_image_footer                =  $data->align_image_footer;
            $printerFooterTemplate->position_img_footer               =  $data->position_img_footer;
            $printerFooterTemplate->footer_image_width                =  $data->footer_image_width;
            $printerFooterTemplate->footer_image_height               =  $data->footer_image_height;
            $printerFooterTemplate->footer_image_border_width         =  $data->footer_image_border_width;
            $printerFooterTemplate->footer_image_border_color         =  $data->footer_image_border_color;
            $printerFooterTemplate->footer_image_border_style         =  $data->footer_image_border_style;
            $printerFooterTemplate->footer_image_border_radius        =  $data->footer_image_border_radius;
            $printerFooterTemplate->footer_image_box_width            =  $data->footer_image_box_width;
            $printerFooterTemplate->footer_image_box_height           =  $data->footer_image_box_height;
            $printerFooterTemplate->footer_image_box_margin           =  $data->footer_image_box_margin;
            $printerFooterTemplate->footer_box_image_background       =  $data->footer_box_image_background;
            $printerFooterTemplate->footer_box_image_color            =  $data->footer_box_image_color;
            $printerFooterTemplate->position_box_footer_align         =  $data->position_box_footer_align;
            $printerFooterTemplate->footer_image_box_background       =  $data->footer_image_box_background;
            $printerFooterTemplate->footer_image_box_border_width     =  $data->footer_image_box_border_width;
            $printerFooterTemplate->footer_image_box_border_style     =  $data->footer_image_box_border_style;
            $printerFooterTemplate->footer_image_box_border_color     =  $data->footer_image_box_border_color;
            $printerFooterTemplate->footer_image_box_border_radius    =  $data->footer_image_box_border_radius;
            $printerFooterTemplate->footer_other_view                 =  ($data->footer_other_view)?true:false;
            $printerFooterTemplate->align_other_footer                =  $data->align_other_footer;
            $printerFooterTemplate->other_background_footer           =  $data->other_background_footer;
            $printerFooterTemplate->footer_other_width                =  $data->footer_other_width;
            $printerFooterTemplate->footer_other_border_radius        =  $data->footer_other_border_radius;
            $printerFooterTemplate->footer_other_border_width         =  $data->footer_other_border_width;
            $printerFooterTemplate->footer_other_border_style         =  $data->footer_other_border_style;
            $printerFooterTemplate->footer_other_border_color         =  $data->footer_other_border_color;
            $printerFooterTemplate->footer_other_position             =  $data->footer_other_position;
            $printerFooterTemplate->footer_other_top                  =  $data->footer_other_top;
            $printerFooterTemplate->footer_other_left                 =  $data->footer_other_left;
            $printerFooterTemplate->footer_other_right                =  $data->footer_other_right;
            $printerFooterTemplate->footer_other_bottom               =  $data->footer_other_bottom;
            $printerFooterTemplate->footer_tax_align                  =  $data->footer_tax_align;
            $printerFooterTemplate->footer_tax_font_size              =  $data->footer_tax_font_size;
            $printerFooterTemplate->footer_tax_width                  =  $data->footer_tax_width;
            $printerFooterTemplate->footer_tax_letter                 =  $data->footer_tax_letter;
            $printerFooterTemplate->footer_tax_border_width           =  $data->footer_tax_border_width;
            $printerFooterTemplate->footer_tax_border_style           =  $data->footer_tax_border_style;
            $printerFooterTemplate->footer_tax_border_color           =  $data->footer_tax_border_color;
            $printerFooterTemplate->footer_tax_padding_top            =  $data->footer_tax_padding_top;
            $printerFooterTemplate->footer_tax_padding_left           =  $data->footer_tax_padding_left;
            $printerFooterTemplate->footer_tax_padding_right          =  $data->footer_tax_padding_right;
            $printerFooterTemplate->footer_tax_padding_bottom         =  $data->footer_tax_padding_bottom;
            $printerFooterTemplate->footer_tax_position               =  $data->footer_tax_position;
            $printerFooterTemplate->footer_tax_top                    =  $data->footer_tax_top;
            $printerFooterTemplate->footer_tax_bottom                 =  $data->footer_tax_bottom;
            $printerFooterTemplate->footer_tax_left                   =  $data->footer_tax_left;
            $printerFooterTemplate->footer_tax_right                  =  $data->footer_tax_right;
            $printerFooterTemplate->footer_address_align              =  $data->footer_address_align;  
            $printerFooterTemplate->footer_address_font_size          =  $data->footer_address_font_size;
            $printerFooterTemplate->footer_address_width              =  $data->footer_address_width;
            $printerFooterTemplate->footer_address_letter             =  $data->footer_address_letter;
            $printerFooterTemplate->footer_address_border_width       =  $data->footer_address_border_width;
            $printerFooterTemplate->footer_address_border_style       =  $data->footer_address_border_style;
            $printerFooterTemplate->footer_address_border_color       =  $data->footer_address_border_color;
            $printerFooterTemplate->footer_address_padding_top        =  $data->footer_address_padding_top;
            $printerFooterTemplate->footer_address_padding_left       =  $data->footer_address_padding_left;
            $printerFooterTemplate->footer_address_padding_right      =  $data->footer_address_padding_right;
            $printerFooterTemplate->footer_address_padding_bottom     =  $data->footer_address_padding_bottom;
            $printerFooterTemplate->footer_address_position           =  $data->footer_address_position;
            $printerFooterTemplate->footer_address_top                =  $data->footer_address_top;
            $printerFooterTemplate->footer_address_bottom             =  $data->footer_address_bottom;
            $printerFooterTemplate->footer_address_left               =  $data->footer_address_left;
            $printerFooterTemplate->footer_address_right              =  $data->footer_address_right;
            $printerFooterTemplate->footer_bill_align                 =  $data->footer_bill_align;
            $printerFooterTemplate->footer_bill_font_size             =  $data->footer_bill_font_size;
            $printerFooterTemplate->footer_bill_width                 =  $data->footer_bill_width;
            $printerFooterTemplate->footer_bill_letter                =  $data->footer_bill_letter;
            $printerFooterTemplate->footer_bill_border_width          =  $data->footer_bill_border_width;
            $printerFooterTemplate->footer_bill_border_style          =  $data->footer_bill_border_style;
            $printerFooterTemplate->footer_bill_border_color          =  $data->footer_bill_border_color;
            $printerFooterTemplate->footer_bill_padding_top           =  $data->footer_bill_padding_top;
            $printerFooterTemplate->footer_bill_padding_left          =  $data->footer_bill_padding_left;
            $printerFooterTemplate->footer_bill_padding_right         =  $data->footer_bill_padding_right;
            $printerFooterTemplate->footer_bill_padding_bottom        =  $data->footer_bill_padding_bottom;
            $printerFooterTemplate->footer_bill_position              =  $data->footer_bill_position;
            $printerFooterTemplate->footer_bill_top                   =  $data->footer_bill_top;
            $printerFooterTemplate->footer_bill_bottom                =  $data->footer_bill_bottom;
            $printerFooterTemplate->footer_bill_left                  =  $data->footer_bill_left;
            $printerFooterTemplate->footer_bill_right                 =  $data->footer_bill_right;
            $printerFooterTemplate->footer_line_view                  =  ($data->footer_line_view)?true:false;
            $printerFooterTemplate->footer_line_height                =  $data->footer_line_height;
            $printerFooterTemplate->footer_line_width                 =  $data->footer_line_width;
            $printerFooterTemplate->footer_line_color                 =  $data->footer_line_color;
            $printerFooterTemplate->footer_line_margin_top            =  $data->footer_line_margin_top;
            $printerFooterTemplate->footer_line_margin_bottom         =  $data->footer_line_margin_bottom;
            $printerFooterTemplate->footer_line_radius                =  $data->footer_line_radius;
            $printerFooterTemplate->footer_line_border_width          =  $data->footer_line_border_width;
            $printerFooterTemplate->footer_line_border_style          =  $data->footer_line_border_style;
            $printerFooterTemplate->footer_line_border_color          =  $data->footer_line_border_color;
            $printerFooterTemplate->page_number_view                  =  ($data->page_number_view!=null)?true:false;
            $printerFooterTemplate->update();
            $Contain = PrinterTemplateContain::where("printer_templates_id",$printerTemplate->id)->first();
           
            PrinterTemplateContain::updateTemplateContain($data,$Contain,$request);
        }
    }
    // delete
    public static function destroyTemplate($id,$request){
        $printerTemplate         =  PrinterTemplate::find($id);
        $printerFooterTemplate   =  PrinterFooterTemplate::where("printer_template_id",$id)->first();
        $printerContentTemplate  =  PrinterContentTemplate::where("printer_template_id",$id)->first();
        $PrinterTemplateContain  =  PrinterTemplateContain::where("printer_templates_id",$id)->first();
        if(!empty($PrinterTemplateContain)){
            $PrinterTemplateContain->delete();
        }
        if(!empty($printerFooterTemplate)){
            $printerFooterTemplate->delete();
        }
        if(!empty($printerContentTemplate)){
            $printerContentTemplate->delete();
        }
        if(!empty($printerTemplate)){
            $printerTemplate->delete();
        }
    }


}
